// Code generated by go-swagger; DO NOT EDIT.

package projects

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetProjectIDParams creates a new GetProjectIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectIDParams() *GetProjectIDParams {
	return NewGetProjectIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetProjectIDParamsWithTimeout creates a new GetProjectIDParams object
// with the ability to set a timeout on a request.
func NewGetProjectIDParamsWithTimeout(timeout time.Duration) *GetProjectIDParams {
	return &GetProjectIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetProjectIDParamsWithContext creates a new GetProjectIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDParams].
func NewGetProjectIDParamsWithContext(ctx context.Context) *GetProjectIDParams {
	return &GetProjectIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetProjectIDParamsWithHTTPClient creates a new GetProjectIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectIDParamsWithHTTPClient(client *http.Client) *GetProjectIDParams {
	return &GetProjectIDParams{
		HTTPClient: client,
	}
}

/*
GetProjectIDParams contains all the parameters to send to the API endpoint

	for the get project ID operation.

	Typically these are written to a http.Request.
*/
type GetProjectIDParams struct {

	/* ID.

	   Project ID
	*/
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDParams) WithDefaults() *GetProjectIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project ID params.
func (o *GetProjectIDParams) WithTimeout(timeout time.Duration) *GetProjectIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project ID params.
func (o *GetProjectIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get project ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDParams].
func (o *GetProjectIDParams) WithContext(ctx context.Context) *GetProjectIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDParams].
func (o *GetProjectIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get project ID params.
func (o *GetProjectIDParams) WithHTTPClient(client *http.Client) *GetProjectIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project ID params.
func (o *GetProjectIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get project ID params.
func (o *GetProjectIDParams) WithID(id int64) *GetProjectIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project ID params.
func (o *GetProjectIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetProjectIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
