// Code generated by go-swagger; DO NOT EDIT.

package projects

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetProjectIDReader is a Reader for the GetProjectID structure.
type GetProjectIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProjectIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProjectIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProjectIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProjectIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /project/{id}] GetProjectID", response, response.Code())
	}
}

// NewGetProjectIDOK creates a GetProjectIDOK with default headers values
func NewGetProjectIDOK() *GetProjectIDOK {
	return &GetProjectIDOK{}
}

/*
GetProjectIDOK describes a response with status code 200, with default header values.

OK
*/
type GetProjectIDOK struct {
	Payload *models.InternalModulesProjectHandlerProjectResponse
}

// IsSuccess returns true when this get project Id o k response has a 2xx status code
func (o *GetProjectIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project Id o k response has a 3xx status code
func (o *GetProjectIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id o k response has a 4xx status code
func (o *GetProjectIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project Id o k response has a 5xx status code
func (o *GetProjectIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id o k response a status code equal to that given
func (o *GetProjectIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project Id o k response
func (o *GetProjectIDOK) Code() int {
	return 200
}

func (o *GetProjectIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdOK %s", 200, payload)
}

func (o *GetProjectIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdOK %s", 200, payload)
}

func (o *GetProjectIDOK) GetPayload() *models.InternalModulesProjectHandlerProjectResponse {
	return o.Payload
}

func (o *GetProjectIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalModulesProjectHandlerProjectResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDBadRequest creates a GetProjectIDBadRequest with default headers values
func NewGetProjectIDBadRequest() *GetProjectIDBadRequest {
	return &GetProjectIDBadRequest{}
}

/*
GetProjectIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProjectIDBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id bad request response has a 2xx status code
func (o *GetProjectIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id bad request response has a 3xx status code
func (o *GetProjectIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id bad request response has a 4xx status code
func (o *GetProjectIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project Id bad request response has a 5xx status code
func (o *GetProjectIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id bad request response a status code equal to that given
func (o *GetProjectIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get project Id bad request response
func (o *GetProjectIDBadRequest) Code() int {
	return 400
}

func (o *GetProjectIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdBadRequest %s", 400, payload)
}

func (o *GetProjectIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdBadRequest %s", 400, payload)
}

func (o *GetProjectIDBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDUnauthorized creates a GetProjectIDUnauthorized with default headers values
func NewGetProjectIDUnauthorized() *GetProjectIDUnauthorized {
	return &GetProjectIDUnauthorized{}
}

/*
GetProjectIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProjectIDUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id unauthorized response has a 2xx status code
func (o *GetProjectIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id unauthorized response has a 3xx status code
func (o *GetProjectIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id unauthorized response has a 4xx status code
func (o *GetProjectIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project Id unauthorized response has a 5xx status code
func (o *GetProjectIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id unauthorized response a status code equal to that given
func (o *GetProjectIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get project Id unauthorized response
func (o *GetProjectIDUnauthorized) Code() int {
	return 401
}

func (o *GetProjectIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdUnauthorized %s", 401, payload)
}

func (o *GetProjectIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdUnauthorized %s", 401, payload)
}

func (o *GetProjectIDUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDNotFound creates a GetProjectIDNotFound with default headers values
func NewGetProjectIDNotFound() *GetProjectIDNotFound {
	return &GetProjectIDNotFound{}
}

/*
GetProjectIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProjectIDNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id not found response has a 2xx status code
func (o *GetProjectIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id not found response has a 3xx status code
func (o *GetProjectIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id not found response has a 4xx status code
func (o *GetProjectIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project Id not found response has a 5xx status code
func (o *GetProjectIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id not found response a status code equal to that given
func (o *GetProjectIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get project Id not found response
func (o *GetProjectIDNotFound) Code() int {
	return 404
}

func (o *GetProjectIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdNotFound %s", 404, payload)
}

func (o *GetProjectIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdNotFound %s", 404, payload)
}

func (o *GetProjectIDNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDInternalServerError creates a GetProjectIDInternalServerError with default headers values
func NewGetProjectIDInternalServerError() *GetProjectIDInternalServerError {
	return &GetProjectIDInternalServerError{}
}

/*
GetProjectIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProjectIDInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id internal server error response has a 2xx status code
func (o *GetProjectIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id internal server error response has a 3xx status code
func (o *GetProjectIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id internal server error response has a 4xx status code
func (o *GetProjectIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project Id internal server error response has a 5xx status code
func (o *GetProjectIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get project Id internal server error response a status code equal to that given
func (o *GetProjectIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get project Id internal server error response
func (o *GetProjectIDInternalServerError) Code() int {
	return 500
}

func (o *GetProjectIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdInternalServerError %s", 500, payload)
}

func (o *GetProjectIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}][%d] getProjectIdInternalServerError %s", 500, payload)
}

func (o *GetProjectIDInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
