// Code generated by go-swagger; DO NOT EDIT.

package projects

import (
	"context"
	"net/http"
	"time"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostProjectParams creates a new PostProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProjectParams() *PostProjectParams {
	return NewPostProjectParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostProjectParamsWithTimeout creates a new PostProjectParams object
// with the ability to set a timeout on a request.
func NewPostProjectParamsWithTimeout(timeout time.Duration) *PostProjectParams {
	return &PostProjectParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostProjectParamsWithContext creates a new PostProjectParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostProjectParams].
func NewPostProjectParamsWithContext(ctx context.Context) *PostProjectParams {
	return &PostProjectParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostProjectParamsWithHTTPClient creates a new PostProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProjectParamsWithHTTPClient(client *http.Client) *PostProjectParams {
	return &PostProjectParams{
		HTTPClient: client,
	}
}

/*
PostProjectParams contains all the parameters to send to the API endpoint

	for the post project operation.

	Typically these are written to a http.Request.
*/
type PostProjectParams struct {

	/* Project.

	   Project data
	*/
	Project *models.InternalModulesProjectHandlerProjectCreateRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectParams) WithDefaults() *PostProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post project params.
func (o *PostProjectParams) WithTimeout(timeout time.Duration) *PostProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post project params.
func (o *PostProjectParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post project params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostProjectParams].
func (o *PostProjectParams) WithContext(ctx context.Context) *PostProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post project params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostProjectParams].
func (o *PostProjectParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post project params.
func (o *PostProjectParams) WithHTTPClient(client *http.Client) *PostProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post project params.
func (o *PostProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the post project params.
func (o *PostProjectParams) WithProject(project *models.InternalModulesProjectHandlerProjectCreateRequest) *PostProjectParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the post project params.
func (o *PostProjectParams) SetProject(project *models.InternalModulesProjectHandlerProjectCreateRequest) {
	o.Project = project
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Project != nil {
		if err := r.SetBodyParam(o.Project); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
