// Code generated by go-swagger; DO NOT EDIT.

package projects

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutProjectIDReader is a Reader for the PutProjectID structure.
type PutProjectIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutProjectIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutProjectIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutProjectIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutProjectIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutProjectIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutProjectIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /project/{id}] PutProjectID", response, response.Code())
	}
}

// NewPutProjectIDOK creates a PutProjectIDOK with default headers values
func NewPutProjectIDOK() *PutProjectIDOK {
	return &PutProjectIDOK{}
}

/*
PutProjectIDOK describes a response with status code 200, with default header values.

OK
*/
type PutProjectIDOK struct {
	Payload *models.InternalModulesProjectHandlerProjectResponse
}

// IsSuccess returns true when this put project Id o k response has a 2xx status code
func (o *PutProjectIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put project Id o k response has a 3xx status code
func (o *PutProjectIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id o k response has a 4xx status code
func (o *PutProjectIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put project Id o k response has a 5xx status code
func (o *PutProjectIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put project Id o k response a status code equal to that given
func (o *PutProjectIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put project Id o k response
func (o *PutProjectIDOK) Code() int {
	return 200
}

func (o *PutProjectIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdOK %s", 200, payload)
}

func (o *PutProjectIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdOK %s", 200, payload)
}

func (o *PutProjectIDOK) GetPayload() *models.InternalModulesProjectHandlerProjectResponse {
	return o.Payload
}

func (o *PutProjectIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalModulesProjectHandlerProjectResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutProjectIDBadRequest creates a PutProjectIDBadRequest with default headers values
func NewPutProjectIDBadRequest() *PutProjectIDBadRequest {
	return &PutProjectIDBadRequest{}
}

/*
PutProjectIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutProjectIDBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this put project Id bad request response has a 2xx status code
func (o *PutProjectIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project Id bad request response has a 3xx status code
func (o *PutProjectIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id bad request response has a 4xx status code
func (o *PutProjectIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put project Id bad request response has a 5xx status code
func (o *PutProjectIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put project Id bad request response a status code equal to that given
func (o *PutProjectIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put project Id bad request response
func (o *PutProjectIDBadRequest) Code() int {
	return 400
}

func (o *PutProjectIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdBadRequest %s", 400, payload)
}

func (o *PutProjectIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdBadRequest %s", 400, payload)
}

func (o *PutProjectIDBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *PutProjectIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutProjectIDUnauthorized creates a PutProjectIDUnauthorized with default headers values
func NewPutProjectIDUnauthorized() *PutProjectIDUnauthorized {
	return &PutProjectIDUnauthorized{}
}

/*
PutProjectIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PutProjectIDUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this put project Id unauthorized response has a 2xx status code
func (o *PutProjectIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project Id unauthorized response has a 3xx status code
func (o *PutProjectIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id unauthorized response has a 4xx status code
func (o *PutProjectIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this put project Id unauthorized response has a 5xx status code
func (o *PutProjectIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this put project Id unauthorized response a status code equal to that given
func (o *PutProjectIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the put project Id unauthorized response
func (o *PutProjectIDUnauthorized) Code() int {
	return 401
}

func (o *PutProjectIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdUnauthorized %s", 401, payload)
}

func (o *PutProjectIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdUnauthorized %s", 401, payload)
}

func (o *PutProjectIDUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *PutProjectIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutProjectIDNotFound creates a PutProjectIDNotFound with default headers values
func NewPutProjectIDNotFound() *PutProjectIDNotFound {
	return &PutProjectIDNotFound{}
}

/*
PutProjectIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutProjectIDNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this put project Id not found response has a 2xx status code
func (o *PutProjectIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project Id not found response has a 3xx status code
func (o *PutProjectIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id not found response has a 4xx status code
func (o *PutProjectIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put project Id not found response has a 5xx status code
func (o *PutProjectIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put project Id not found response a status code equal to that given
func (o *PutProjectIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put project Id not found response
func (o *PutProjectIDNotFound) Code() int {
	return 404
}

func (o *PutProjectIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdNotFound %s", 404, payload)
}

func (o *PutProjectIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdNotFound %s", 404, payload)
}

func (o *PutProjectIDNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *PutProjectIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutProjectIDInternalServerError creates a PutProjectIDInternalServerError with default headers values
func NewPutProjectIDInternalServerError() *PutProjectIDInternalServerError {
	return &PutProjectIDInternalServerError{}
}

/*
PutProjectIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutProjectIDInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this put project Id internal server error response has a 2xx status code
func (o *PutProjectIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project Id internal server error response has a 3xx status code
func (o *PutProjectIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id internal server error response has a 4xx status code
func (o *PutProjectIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put project Id internal server error response has a 5xx status code
func (o *PutProjectIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put project Id internal server error response a status code equal to that given
func (o *PutProjectIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put project Id internal server error response
func (o *PutProjectIDInternalServerError) Code() int {
	return 500
}

func (o *PutProjectIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdInternalServerError %s", 500, payload)
}

func (o *PutProjectIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}][%d] putProjectIdInternalServerError %s", 500, payload)
}

func (o *PutProjectIDInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *PutProjectIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
