// Code generated by go-swagger; DO NOT EDIT.

package projects

import (
	"context"
	"net/http"
	"time"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewPutProjectIDParams creates a new PutProjectIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProjectIDParams() *PutProjectIDParams {
	return NewPutProjectIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutProjectIDParamsWithTimeout creates a new PutProjectIDParams object
// with the ability to set a timeout on a request.
func NewPutProjectIDParamsWithTimeout(timeout time.Duration) *PutProjectIDParams {
	return &PutProjectIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutProjectIDParamsWithContext creates a new PutProjectIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProjectIDParams].
func NewPutProjectIDParamsWithContext(ctx context.Context) *PutProjectIDParams {
	return &PutProjectIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutProjectIDParamsWithHTTPClient creates a new PutProjectIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProjectIDParamsWithHTTPClient(client *http.Client) *PutProjectIDParams {
	return &PutProjectIDParams{
		HTTPClient: client,
	}
}

/*
PutProjectIDParams contains all the parameters to send to the API endpoint

	for the put project ID operation.

	Typically these are written to a http.Request.
*/
type PutProjectIDParams struct {

	/* ID.

	   Project ID
	*/
	ID int64

	/* Project.

	   Project data
	*/
	Project *models.InternalModulesProjectHandlerProjectUpdateRequest

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectIDParams) WithDefaults() *PutProjectIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put project ID params.
func (o *PutProjectIDParams) WithTimeout(timeout time.Duration) *PutProjectIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put project ID params.
func (o *PutProjectIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put project ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProjectIDParams].
func (o *PutProjectIDParams) WithContext(ctx context.Context) *PutProjectIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put project ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutProjectIDParams].
func (o *PutProjectIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put project ID params.
func (o *PutProjectIDParams) WithHTTPClient(client *http.Client) *PutProjectIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put project ID params.
func (o *PutProjectIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put project ID params.
func (o *PutProjectIDParams) WithID(id int64) *PutProjectIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put project ID params.
func (o *PutProjectIDParams) SetID(id int64) {
	o.ID = id
}

// WithProject adds the project to the put project ID params.
func (o *PutProjectIDParams) WithProject(project *models.InternalModulesProjectHandlerProjectUpdateRequest) *PutProjectIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the put project ID params.
func (o *PutProjectIDParams) SetProject(project *models.InternalModulesProjectHandlerProjectUpdateRequest) {
	o.Project = project
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutProjectIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}
	if o.Project != nil {
		if err := r.SetBodyParam(o.Project); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
