// Code generated by go-swagger; DO NOT EDIT.

package keystore

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetKeystoreReader is a Reader for the GetKeystore structure.
type GetKeystoreReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKeystoreReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetKeystoreOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetKeystoreUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetKeystoreInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /keystore] GetKeystore", response, response.Code())
	}
}

// NewGetKeystoreOK creates a GetKeystoreOK with default headers values
func NewGetKeystoreOK() *GetKeystoreOK {
	return &GetKeystoreOK{}
}

/*
GetKeystoreOK describes a response with status code 200, with default header values.

OK
*/
type GetKeystoreOK struct {
	Payload any
}

// IsSuccess returns true when this get keystore o k response has a 2xx status code
func (o *GetKeystoreOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get keystore o k response has a 3xx status code
func (o *GetKeystoreOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get keystore o k response has a 4xx status code
func (o *GetKeystoreOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get keystore o k response has a 5xx status code
func (o *GetKeystoreOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get keystore o k response a status code equal to that given
func (o *GetKeystoreOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get keystore o k response
func (o *GetKeystoreOK) Code() int {
	return 200
}

func (o *GetKeystoreOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /keystore][%d] getKeystoreOK %s", 200, payload)
}

func (o *GetKeystoreOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /keystore][%d] getKeystoreOK %s", 200, payload)
}

func (o *GetKeystoreOK) GetPayload() any {
	return o.Payload
}

func (o *GetKeystoreOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetKeystoreUnauthorized creates a GetKeystoreUnauthorized with default headers values
func NewGetKeystoreUnauthorized() *GetKeystoreUnauthorized {
	return &GetKeystoreUnauthorized{}
}

/*
GetKeystoreUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetKeystoreUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this get keystore unauthorized response has a 2xx status code
func (o *GetKeystoreUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get keystore unauthorized response has a 3xx status code
func (o *GetKeystoreUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get keystore unauthorized response has a 4xx status code
func (o *GetKeystoreUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get keystore unauthorized response has a 5xx status code
func (o *GetKeystoreUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get keystore unauthorized response a status code equal to that given
func (o *GetKeystoreUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get keystore unauthorized response
func (o *GetKeystoreUnauthorized) Code() int {
	return 401
}

func (o *GetKeystoreUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /keystore][%d] getKeystoreUnauthorized %s", 401, payload)
}

func (o *GetKeystoreUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /keystore][%d] getKeystoreUnauthorized %s", 401, payload)
}

func (o *GetKeystoreUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetKeystoreUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetKeystoreInternalServerError creates a GetKeystoreInternalServerError with default headers values
func NewGetKeystoreInternalServerError() *GetKeystoreInternalServerError {
	return &GetKeystoreInternalServerError{}
}

/*
GetKeystoreInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetKeystoreInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this get keystore internal server error response has a 2xx status code
func (o *GetKeystoreInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get keystore internal server error response has a 3xx status code
func (o *GetKeystoreInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get keystore internal server error response has a 4xx status code
func (o *GetKeystoreInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get keystore internal server error response has a 5xx status code
func (o *GetKeystoreInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get keystore internal server error response a status code equal to that given
func (o *GetKeystoreInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get keystore internal server error response
func (o *GetKeystoreInternalServerError) Code() int {
	return 500
}

func (o *GetKeystoreInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /keystore][%d] getKeystoreInternalServerError %s", 500, payload)
}

func (o *GetKeystoreInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /keystore][%d] getKeystoreInternalServerError %s", 500, payload)
}

func (o *GetKeystoreInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetKeystoreInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
