// Code generated by go-swagger; DO NOT EDIT.

package keystore

import (
	"context"
	"net/http"
	"time"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostKeystoreParams creates a new PostKeystoreParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostKeystoreParams() *PostKeystoreParams {
	return NewPostKeystoreParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostKeystoreParamsWithTimeout creates a new PostKeystoreParams object
// with the ability to set a timeout on a request.
func NewPostKeystoreParamsWithTimeout(timeout time.Duration) *PostKeystoreParams {
	return &PostKeystoreParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostKeystoreParamsWithContext creates a new PostKeystoreParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostKeystoreParams].
func NewPostKeystoreParamsWithContext(ctx context.Context) *PostKeystoreParams {
	return &PostKeystoreParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostKeystoreParamsWithHTTPClient creates a new PostKeystoreParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostKeystoreParamsWithHTTPClient(client *http.Client) *PostKeystoreParams {
	return &PostKeystoreParams{
		HTTPClient: client,
	}
}

/*
PostKeystoreParams contains all the parameters to send to the API endpoint

	for the post keystore operation.

	Typically these are written to a http.Request.
*/
type PostKeystoreParams struct {

	/* Keystore.

	   Keystore data
	*/
	Keystore *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseKeystore

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post keystore params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostKeystoreParams) WithDefaults() *PostKeystoreParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post keystore params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostKeystoreParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post keystore params.
func (o *PostKeystoreParams) WithTimeout(timeout time.Duration) *PostKeystoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post keystore params.
func (o *PostKeystoreParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post keystore params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostKeystoreParams].
func (o *PostKeystoreParams) WithContext(ctx context.Context) *PostKeystoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post keystore params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostKeystoreParams].
func (o *PostKeystoreParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post keystore params.
func (o *PostKeystoreParams) WithHTTPClient(client *http.Client) *PostKeystoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post keystore params.
func (o *PostKeystoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKeystore adds the keystore to the post keystore params.
func (o *PostKeystoreParams) WithKeystore(keystore *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseKeystore) *PostKeystoreParams {
	o.SetKeystore(keystore)
	return o
}

// SetKeystore adds the keystore to the post keystore params.
func (o *PostKeystoreParams) SetKeystore(keystore *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseKeystore) {
	o.Keystore = keystore
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostKeystoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Keystore != nil {
		if err := r.SetBodyParam(o.Keystore); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
