// Code generated by go-swagger; DO NOT EDIT.

package github

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteGithubDisconnectParams creates a new DeleteGithubDisconnectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteGithubDisconnectParams() *DeleteGithubDisconnectParams {
	return NewDeleteGithubDisconnectParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteGithubDisconnectParamsWithTimeout creates a new DeleteGithubDisconnectParams object
// with the ability to set a timeout on a request.
func NewDeleteGithubDisconnectParamsWithTimeout(timeout time.Duration) *DeleteGithubDisconnectParams {
	return &DeleteGithubDisconnectParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteGithubDisconnectParamsWithContext creates a new DeleteGithubDisconnectParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteGithubDisconnectParams].
func NewDeleteGithubDisconnectParamsWithContext(ctx context.Context) *DeleteGithubDisconnectParams {
	return &DeleteGithubDisconnectParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteGithubDisconnectParamsWithHTTPClient creates a new DeleteGithubDisconnectParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteGithubDisconnectParamsWithHTTPClient(client *http.Client) *DeleteGithubDisconnectParams {
	return &DeleteGithubDisconnectParams{
		HTTPClient: client,
	}
}

/*
DeleteGithubDisconnectParams contains all the parameters to send to the API endpoint

	for the delete github disconnect operation.

	Typically these are written to a http.Request.
*/
type DeleteGithubDisconnectParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete github disconnect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteGithubDisconnectParams) WithDefaults() *DeleteGithubDisconnectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete github disconnect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteGithubDisconnectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete github disconnect params.
func (o *DeleteGithubDisconnectParams) WithTimeout(timeout time.Duration) *DeleteGithubDisconnectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete github disconnect params.
func (o *DeleteGithubDisconnectParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete github disconnect params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteGithubDisconnectParams].
func (o *DeleteGithubDisconnectParams) WithContext(ctx context.Context) *DeleteGithubDisconnectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete github disconnect params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteGithubDisconnectParams].
func (o *DeleteGithubDisconnectParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete github disconnect params.
func (o *DeleteGithubDisconnectParams) WithHTTPClient(client *http.Client) *DeleteGithubDisconnectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete github disconnect params.
func (o *DeleteGithubDisconnectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteGithubDisconnectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
