// Code generated by go-swagger; DO NOT EDIT.

package github

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new github API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new github API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new github API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for github API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// DeleteGithubDisconnect déconnecte l utilisateur courant de git hub.
	DeleteGithubDisconnect(params *DeleteGithubDisconnectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteGithubDisconnectOK, error)

	// DeleteGithubDisconnectContext déconnecte l utilisateur courant de git hub.
	DeleteGithubDisconnectContext(ctx context.Context, params *DeleteGithubDisconnectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteGithubDisconnectOK, error)

	// GetGithubInstallation vérifie l existence d une installation git hub par installation id.
	GetGithubInstallation(params *GetGithubInstallationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubInstallationOK, error)

	// GetGithubInstallationContext vérifie l existence d une installation git hub par installation id.
	GetGithubInstallationContext(ctx context.Context, params *GetGithubInstallationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubInstallationOK, error)

	// GetGithubInstallations vérifie si l utilisateur a une installation git hub.
	GetGithubInstallations(params *GetGithubInstallationsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubInstallationsOK, error)

	// GetGithubInstallationsContext vérifie si l utilisateur a une installation git hub.
	GetGithubInstallationsContext(ctx context.Context, params *GetGithubInstallationsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubInstallationsOK, error)

	// GetGithubPubspecPath trouve le chemin de pubspec yaml dans un repo.
	GetGithubPubspecPath(params *GetGithubPubspecPathParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubPubspecPathOK, error)

	// GetGithubPubspecPathContext trouve le chemin de pubspec yaml dans un repo.
	GetGithubPubspecPathContext(ctx context.Context, params *GetGithubPubspecPathParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubPubspecPathOK, error)

	// GetGithubRepo récupère l arborescence d un repo git hub.
	GetGithubRepo(params *GetGithubRepoParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubRepoOK, error)

	// GetGithubRepoContext récupère l arborescence d un repo git hub.
	GetGithubRepoContext(ctx context.Context, params *GetGithubRepoParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubRepoOK, error)

	// GetGithubRepos get git hub repositories.
	GetGithubRepos(params *GetGithubReposParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubReposOK, error)

	// GetGithubReposContext get git hub repositories.
	GetGithubReposContext(ctx context.Context, params *GetGithubReposParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubReposOK, error)

	// PostGithubPostInstallation enregistre ou met à jour une installation git hub pour l utilisateur authentifié.
	PostGithubPostInstallation(params *PostGithubPostInstallationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostGithubPostInstallationOK, error)

	// PostGithubPostInstallationContext enregistre ou met à jour une installation git hub pour l utilisateur authentifié.
	PostGithubPostInstallationContext(ctx context.Context, params *PostGithubPostInstallationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostGithubPostInstallationOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
DeleteGithubDisconnectdéconnectes l utilisateur courant de git hub.

Supprime l'enregistrement `GithubInstallation` de l'utilisateur courant et tente de supprimer l'installation via l'API GitHub.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.DeleteGithubDisconnectContext] instead.
*/
func (a *Client) DeleteGithubDisconnect(params *DeleteGithubDisconnectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteGithubDisconnectOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteGithubDisconnectContext(ctx, params, authInfo, opts...)
}

/*
DeleteGithubDisconnectContextdéconnectes l utilisateur courant de git hub.

Supprime l'enregistrement `GithubInstallation` de l'utilisateur courant et tente de supprimer l'installation via l'API GitHub.

Do not use the deprecated [DeleteGithubDisconnectParams.Context] with this method: it would be ignored.
*/
func (a *Client) DeleteGithubDisconnectContext(ctx context.Context, params *DeleteGithubDisconnectParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteGithubDisconnectOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteGithubDisconnectParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "DeleteGithubDisconnect",
		Method:             "DELETE",
		PathPattern:        "/github/disconnect",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteGithubDisconnectReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteGithubDisconnectOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteGithubDisconnect: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetGithubInstallationvérifies l existence d une installation git hub par installation id.

Retourne l'enregistrement GithubInstallation correspondant à installation_id si présent.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetGithubInstallationContext] instead.
*/
func (a *Client) GetGithubInstallation(params *GetGithubInstallationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubInstallationOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetGithubInstallationContext(ctx, params, authInfo, opts...)
}

/*
GetGithubInstallationContextvérifies l existence d une installation git hub par installation id.

Retourne l'enregistrement GithubInstallation correspondant à installation_id si présent.

Do not use the deprecated [GetGithubInstallationParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetGithubInstallationContext(ctx context.Context, params *GetGithubInstallationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubInstallationOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetGithubInstallationParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetGithubInstallation",
		Method:             "GET",
		PathPattern:        "/github/installation",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGithubInstallationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetGithubInstallationOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetGithubInstallation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetGithubInstallationsvérifies si l utilisateur a une installation git hub.

Retourne l'installation GitHub liée à l'utilisateur authentifié.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetGithubInstallationsContext] instead.
*/
func (a *Client) GetGithubInstallations(params *GetGithubInstallationsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubInstallationsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetGithubInstallationsContext(ctx, params, authInfo, opts...)
}

/*
GetGithubInstallationsContextvérifies si l utilisateur a une installation git hub.

Retourne l'installation GitHub liée à l'utilisateur authentifié.

Do not use the deprecated [GetGithubInstallationsParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetGithubInstallationsContext(ctx context.Context, params *GetGithubInstallationsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubInstallationsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetGithubInstallationsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetGithubInstallations",
		Method:             "GET",
		PathPattern:        "/github/installations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGithubInstallationsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetGithubInstallationsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetGithubInstallations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetGithubPubspecPathtrouves le chemin de pubspec yaml dans un repo.

Parcourt le repo pour renvoyer le path du pubspec.yaml (utilisé pour déterminer build folder).

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetGithubPubspecPathContext] instead.
*/
func (a *Client) GetGithubPubspecPath(params *GetGithubPubspecPathParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubPubspecPathOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetGithubPubspecPathContext(ctx, params, authInfo, opts...)
}

/*
GetGithubPubspecPathContexttrouves le chemin de pubspec yaml dans un repo.

Parcourt le repo pour renvoyer le path du pubspec.yaml (utilisé pour déterminer build folder).

Do not use the deprecated [GetGithubPubspecPathParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetGithubPubspecPathContext(ctx context.Context, params *GetGithubPubspecPathParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubPubspecPathOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetGithubPubspecPathParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetGithubPubspecPath",
		Method:             "GET",
		PathPattern:        "/github/pubspec-path",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGithubPubspecPathReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetGithubPubspecPathOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetGithubPubspecPath: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetGithubReporécupères l arborescence d un repo git hub.

Retourne l'arborescence complète des dossiers d'un dépôt GitHub.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetGithubRepoContext] instead.
*/
func (a *Client) GetGithubRepo(params *GetGithubRepoParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubRepoOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetGithubRepoContext(ctx, params, authInfo, opts...)
}

/*
GetGithubRepoContextrécupères l arborescence d un repo git hub.

Retourne l'arborescence complète des dossiers d'un dépôt GitHub.

Do not use the deprecated [GetGithubRepoParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetGithubRepoContext(ctx context.Context, params *GetGithubRepoParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubRepoOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetGithubRepoParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetGithubRepo",
		Method:             "GET",
		PathPattern:        "/github/repo",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGithubRepoReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetGithubRepoOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetGithubRepo: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetGithubReposgets git hub repositories.

Liste les repos accessibles pour l'installation GitHub de l'utilisateur.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetGithubReposContext] instead.
*/
func (a *Client) GetGithubRepos(params *GetGithubReposParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubReposOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetGithubReposContext(ctx, params, authInfo, opts...)
}

/*
GetGithubReposContextgets git hub repositories.

Liste les repos accessibles pour l'installation GitHub de l'utilisateur.

Do not use the deprecated [GetGithubReposParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetGithubReposContext(ctx context.Context, params *GetGithubReposParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGithubReposOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetGithubReposParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetGithubRepos",
		Method:             "GET",
		PathPattern:        "/github/repos",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGithubReposReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetGithubReposOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetGithubRepos: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostGithubPostInstallationenregistres ou met à jour une installation git hub pour l utilisateur authentifié.

Reçoit l'ID d'installation GitHub et l'associe à l'utilisateur actuel.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostGithubPostInstallationContext] instead.
*/
func (a *Client) PostGithubPostInstallation(params *PostGithubPostInstallationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostGithubPostInstallationOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostGithubPostInstallationContext(ctx, params, authInfo, opts...)
}

/*
PostGithubPostInstallationContextenregistres ou met à jour une installation git hub pour l utilisateur authentifié.

Reçoit l'ID d'installation GitHub et l'associe à l'utilisateur actuel.

Do not use the deprecated [PostGithubPostInstallationParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostGithubPostInstallationContext(ctx context.Context, params *PostGithubPostInstallationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostGithubPostInstallationOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostGithubPostInstallationParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostGithubPostInstallation",
		Method:             "POST",
		PathPattern:        "/github/post-installation",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostGithubPostInstallationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostGithubPostInstallationOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostGithubPostInstallation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [GithubParams].
	ctx context.Context
}
