// Code generated by go-swagger; DO NOT EDIT.

package github

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostGithubPostInstallationReader is a Reader for the PostGithubPostInstallation structure.
type PostGithubPostInstallationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGithubPostInstallationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostGithubPostInstallationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostGithubPostInstallationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /github/post-installation] PostGithubPostInstallation", response, response.Code())
	}
}

// NewPostGithubPostInstallationOK creates a PostGithubPostInstallationOK with default headers values
func NewPostGithubPostInstallationOK() *PostGithubPostInstallationOK {
	return &PostGithubPostInstallationOK{}
}

/*
PostGithubPostInstallationOK describes a response with status code 200, with default header values.

OK
*/
type PostGithubPostInstallationOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse
}

// IsSuccess returns true when this post github post installation o k response has a 2xx status code
func (o *PostGithubPostInstallationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post github post installation o k response has a 3xx status code
func (o *PostGithubPostInstallationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post github post installation o k response has a 4xx status code
func (o *PostGithubPostInstallationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post github post installation o k response has a 5xx status code
func (o *PostGithubPostInstallationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post github post installation o k response a status code equal to that given
func (o *PostGithubPostInstallationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post github post installation o k response
func (o *PostGithubPostInstallationOK) Code() int {
	return 200
}

func (o *PostGithubPostInstallationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /github/post-installation][%d] postGithubPostInstallationOK %s", 200, payload)
}

func (o *PostGithubPostInstallationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /github/post-installation][%d] postGithubPostInstallationOK %s", 200, payload)
}

func (o *PostGithubPostInstallationOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse {
	return o.Payload
}

func (o *PostGithubPostInstallationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostGithubPostInstallationBadRequest creates a PostGithubPostInstallationBadRequest with default headers values
func NewPostGithubPostInstallationBadRequest() *PostGithubPostInstallationBadRequest {
	return &PostGithubPostInstallationBadRequest{}
}

/*
PostGithubPostInstallationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostGithubPostInstallationBadRequest struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModelsAPIErrorResponse
}

// IsSuccess returns true when this post github post installation bad request response has a 2xx status code
func (o *PostGithubPostInstallationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post github post installation bad request response has a 3xx status code
func (o *PostGithubPostInstallationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post github post installation bad request response has a 4xx status code
func (o *PostGithubPostInstallationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post github post installation bad request response has a 5xx status code
func (o *PostGithubPostInstallationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post github post installation bad request response a status code equal to that given
func (o *PostGithubPostInstallationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post github post installation bad request response
func (o *PostGithubPostInstallationBadRequest) Code() int {
	return 400
}

func (o *PostGithubPostInstallationBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /github/post-installation][%d] postGithubPostInstallationBadRequest %s", 400, payload)
}

func (o *PostGithubPostInstallationBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /github/post-installation][%d] postGithubPostInstallationBadRequest %s", 400, payload)
}

func (o *PostGithubPostInstallationBadRequest) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModelsAPIErrorResponse {
	return o.Payload
}

func (o *PostGithubPostInstallationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModelsAPIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
