// Code generated by go-swagger; DO NOT EDIT.

package client

import (
	"maps"

	"github.com/flotio-dev/cli/pkg/api/client/auth"
	"github.com/flotio-dev/cli/pkg/api/client/builds"
	"github.com/flotio-dev/cli/pkg/api/client/config"
	"github.com/flotio-dev/cli/pkg/api/client/environment"
	"github.com/flotio-dev/cli/pkg/api/client/flutter"
	"github.com/flotio-dev/cli/pkg/api/client/github"
	"github.com/flotio-dev/cli/pkg/api/client/google_play_credentials"
	"github.com/flotio-dev/cli/pkg/api/client/keystore"
	"github.com/flotio-dev/cli/pkg/api/client/kubernetes"
	"github.com/flotio-dev/cli/pkg/api/client/projects"
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// Default flotio API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host found in Meta (info) section of spec file.
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath found in Meta (info) section of spec file.
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file.
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new flotio API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *FlotioAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new flotio API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *FlotioAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client.
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	maps.Copy(transport.Producers, cfg.Producers)
	maps.Copy(transport.Consumers, cfg.Consumers)

	return New(transport, formats)
}

// New creates a new flotio API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) *FlotioAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(FlotioAPI)
	cli.Transport = transport
	cli.Auth = auth.New(transport, formats)
	cli.Builds = builds.New(transport, formats)
	cli.Config = config.New(transport, formats)
	cli.Environment = environment.New(transport, formats)
	cli.Flutter = flutter.New(transport, formats)
	cli.Github = github.New(transport, formats)
	cli.GooglePlayCredentials = google_play_credentials.New(transport, formats)
	cli.Keystore = keystore.New(transport, formats)
	cli.Kubernetes = kubernetes.New(transport, formats)
	cli.Projects = projects.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host      string
	BasePath  string
	Schemes   []string
	Producers map[string]runtime.Producer
	Consumers map[string]runtime.Consumer
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// WithProducers overrides the default producers registered by [httptransport.Runtime].
func (cfg *TransportConfig) WithProducers(producers map[string]runtime.Producer) *TransportConfig {
	cfg.Producers = producers
	return cfg
}

// WithConsumers overrides the default consumers registered by [httptransport.Runtime].
func (cfg *TransportConfig) WithConsumers(consumers map[string]runtime.Consumer) *TransportConfig {
	cfg.Consumers = consumers
	return cfg
}

// FlotioAPI is a client for flotio API.
type FlotioAPI struct {
	Auth auth.ClientService

	Builds builds.ClientService

	Config config.ClientService

	Environment environment.ClientService

	Flutter flutter.ClientService

	Github github.ClientService

	GooglePlayCredentials google_play_credentials.ClientService

	Keystore keystore.ClientService

	Kubernetes kubernetes.ClientService

	Projects projects.ClientService

	Transport runtime.ContextualTransport
}

// SetTransport changes the transport on the client and all its subresources.
func (c *FlotioAPI) SetTransport(transport runtime.ContextualTransport) {
	c.Transport = transport
	c.Auth.SetTransport(transport)
	c.Builds.SetTransport(transport)
	c.Config.SetTransport(transport)
	c.Environment.SetTransport(transport)
	c.Flutter.SetTransport(transport)
	c.Github.SetTransport(transport)
	c.GooglePlayCredentials.SetTransport(transport)
	c.Keystore.SetTransport(transport)
	c.Kubernetes.SetTransport(transport)
	c.Projects.SetTransport(transport)
}
