// Code generated by go-swagger; DO NOT EDIT.

package kubernetes

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewPostInternalKubernetesConfigmapParams creates a new PostInternalKubernetesConfigmapParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostInternalKubernetesConfigmapParams() *PostInternalKubernetesConfigmapParams {
	return NewPostInternalKubernetesConfigmapParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostInternalKubernetesConfigmapParamsWithTimeout creates a new PostInternalKubernetesConfigmapParams object
// with the ability to set a timeout on a request.
func NewPostInternalKubernetesConfigmapParamsWithTimeout(timeout time.Duration) *PostInternalKubernetesConfigmapParams {
	return &PostInternalKubernetesConfigmapParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostInternalKubernetesConfigmapParamsWithContext creates a new PostInternalKubernetesConfigmapParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesConfigmapParams].
func NewPostInternalKubernetesConfigmapParamsWithContext(ctx context.Context) *PostInternalKubernetesConfigmapParams {
	return &PostInternalKubernetesConfigmapParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostInternalKubernetesConfigmapParamsWithHTTPClient creates a new PostInternalKubernetesConfigmapParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostInternalKubernetesConfigmapParamsWithHTTPClient(client *http.Client) *PostInternalKubernetesConfigmapParams {
	return &PostInternalKubernetesConfigmapParams{
		HTTPClient: client,
	}
}

/*
PostInternalKubernetesConfigmapParams contains all the parameters to send to the API endpoint

	for the post internal kubernetes configmap operation.

	Typically these are written to a http.Request.
*/
type PostInternalKubernetesConfigmapParams struct {

	/* BuildID.

	   Build ID
	*/
	BuildID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post internal kubernetes configmap params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInternalKubernetesConfigmapParams) WithDefaults() *PostInternalKubernetesConfigmapParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post internal kubernetes configmap params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInternalKubernetesConfigmapParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post internal kubernetes configmap params.
func (o *PostInternalKubernetesConfigmapParams) WithTimeout(timeout time.Duration) *PostInternalKubernetesConfigmapParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post internal kubernetes configmap params.
func (o *PostInternalKubernetesConfigmapParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post internal kubernetes configmap params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesConfigmapParams].
func (o *PostInternalKubernetesConfigmapParams) WithContext(ctx context.Context) *PostInternalKubernetesConfigmapParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post internal kubernetes configmap params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesConfigmapParams].
func (o *PostInternalKubernetesConfigmapParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post internal kubernetes configmap params.
func (o *PostInternalKubernetesConfigmapParams) WithHTTPClient(client *http.Client) *PostInternalKubernetesConfigmapParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post internal kubernetes configmap params.
func (o *PostInternalKubernetesConfigmapParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildID adds the buildID to the post internal kubernetes configmap params.
func (o *PostInternalKubernetesConfigmapParams) WithBuildID(buildID int64) *PostInternalKubernetesConfigmapParams {
	o.SetBuildID(buildID)
	return o
}

// SetBuildID adds the buildId to the post internal kubernetes configmap params.
func (o *PostInternalKubernetesConfigmapParams) SetBuildID(buildID int64) {
	o.BuildID = buildID
}

// WithProjectID adds the projectID to the post internal kubernetes configmap params.
func (o *PostInternalKubernetesConfigmapParams) WithProjectID(projectID int64) *PostInternalKubernetesConfigmapParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the post internal kubernetes configmap params.
func (o *PostInternalKubernetesConfigmapParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostInternalKubernetesConfigmapParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param buildID
	if err := r.SetPathParam("buildID", conv.FormatInteger(o.BuildID)); err != nil {
		return err
	}

	// path param projectID
	if err := r.SetPathParam("projectID", conv.FormatInteger(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
