// Code generated by go-swagger; DO NOT EDIT.

package kubernetes

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostInternalKubernetesPodReader is a Reader for the PostInternalKubernetesPod structure.
type PostInternalKubernetesPodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInternalKubernetesPodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostInternalKubernetesPodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostInternalKubernetesPodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /internal/kubernetes/pod] PostInternalKubernetesPod", response, response.Code())
	}
}

// NewPostInternalKubernetesPodOK creates a PostInternalKubernetesPodOK with default headers values
func NewPostInternalKubernetesPodOK() *PostInternalKubernetesPodOK {
	return &PostInternalKubernetesPodOK{}
}

/*
PostInternalKubernetesPodOK describes a response with status code 200, with default header values.

OK
*/
type PostInternalKubernetesPodOK struct {
}

// IsSuccess returns true when this post internal kubernetes pod o k response has a 2xx status code
func (o *PostInternalKubernetesPodOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post internal kubernetes pod o k response has a 3xx status code
func (o *PostInternalKubernetesPodOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post internal kubernetes pod o k response has a 4xx status code
func (o *PostInternalKubernetesPodOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post internal kubernetes pod o k response has a 5xx status code
func (o *PostInternalKubernetesPodOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post internal kubernetes pod o k response a status code equal to that given
func (o *PostInternalKubernetesPodOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post internal kubernetes pod o k response
func (o *PostInternalKubernetesPodOK) Code() int {
	return 200
}

func (o *PostInternalKubernetesPodOK) Error() string {
	return fmt.Sprintf("[POST /internal/kubernetes/pod][%d] postInternalKubernetesPodOK", 200)
}

func (o *PostInternalKubernetesPodOK) String() string {
	return fmt.Sprintf("[POST /internal/kubernetes/pod][%d] postInternalKubernetesPodOK", 200)
}

func (o *PostInternalKubernetesPodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInternalKubernetesPodInternalServerError creates a PostInternalKubernetesPodInternalServerError with default headers values
func NewPostInternalKubernetesPodInternalServerError() *PostInternalKubernetesPodInternalServerError {
	return &PostInternalKubernetesPodInternalServerError{}
}

/*
PostInternalKubernetesPodInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostInternalKubernetesPodInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this post internal kubernetes pod internal server error response has a 2xx status code
func (o *PostInternalKubernetesPodInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post internal kubernetes pod internal server error response has a 3xx status code
func (o *PostInternalKubernetesPodInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post internal kubernetes pod internal server error response has a 4xx status code
func (o *PostInternalKubernetesPodInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post internal kubernetes pod internal server error response has a 5xx status code
func (o *PostInternalKubernetesPodInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post internal kubernetes pod internal server error response a status code equal to that given
func (o *PostInternalKubernetesPodInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post internal kubernetes pod internal server error response
func (o *PostInternalKubernetesPodInternalServerError) Code() int {
	return 500
}

func (o *PostInternalKubernetesPodInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /internal/kubernetes/pod][%d] postInternalKubernetesPodInternalServerError %s", 500, payload)
}

func (o *PostInternalKubernetesPodInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /internal/kubernetes/pod][%d] postInternalKubernetesPodInternalServerError %s", 500, payload)
}

func (o *PostInternalKubernetesPodInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostInternalKubernetesPodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
