// Code generated by go-swagger; DO NOT EDIT.

package kubernetes

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewPostInternalKubernetesSecretParams creates a new PostInternalKubernetesSecretParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostInternalKubernetesSecretParams() *PostInternalKubernetesSecretParams {
	return NewPostInternalKubernetesSecretParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostInternalKubernetesSecretParamsWithTimeout creates a new PostInternalKubernetesSecretParams object
// with the ability to set a timeout on a request.
func NewPostInternalKubernetesSecretParamsWithTimeout(timeout time.Duration) *PostInternalKubernetesSecretParams {
	return &PostInternalKubernetesSecretParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostInternalKubernetesSecretParamsWithContext creates a new PostInternalKubernetesSecretParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesSecretParams].
func NewPostInternalKubernetesSecretParamsWithContext(ctx context.Context) *PostInternalKubernetesSecretParams {
	return &PostInternalKubernetesSecretParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostInternalKubernetesSecretParamsWithHTTPClient creates a new PostInternalKubernetesSecretParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostInternalKubernetesSecretParamsWithHTTPClient(client *http.Client) *PostInternalKubernetesSecretParams {
	return &PostInternalKubernetesSecretParams{
		HTTPClient: client,
	}
}

/*
PostInternalKubernetesSecretParams contains all the parameters to send to the API endpoint

	for the post internal kubernetes secret operation.

	Typically these are written to a http.Request.
*/
type PostInternalKubernetesSecretParams struct {

	/* BuildID.

	   Build ID
	*/
	BuildID int64

	/* ProjectID.

	   Project ID
	*/
	ProjectID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post internal kubernetes secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInternalKubernetesSecretParams) WithDefaults() *PostInternalKubernetesSecretParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post internal kubernetes secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInternalKubernetesSecretParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post internal kubernetes secret params.
func (o *PostInternalKubernetesSecretParams) WithTimeout(timeout time.Duration) *PostInternalKubernetesSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post internal kubernetes secret params.
func (o *PostInternalKubernetesSecretParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post internal kubernetes secret params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesSecretParams].
func (o *PostInternalKubernetesSecretParams) WithContext(ctx context.Context) *PostInternalKubernetesSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post internal kubernetes secret params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesSecretParams].
func (o *PostInternalKubernetesSecretParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post internal kubernetes secret params.
func (o *PostInternalKubernetesSecretParams) WithHTTPClient(client *http.Client) *PostInternalKubernetesSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post internal kubernetes secret params.
func (o *PostInternalKubernetesSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildID adds the buildID to the post internal kubernetes secret params.
func (o *PostInternalKubernetesSecretParams) WithBuildID(buildID int64) *PostInternalKubernetesSecretParams {
	o.SetBuildID(buildID)
	return o
}

// SetBuildID adds the buildId to the post internal kubernetes secret params.
func (o *PostInternalKubernetesSecretParams) SetBuildID(buildID int64) {
	o.BuildID = buildID
}

// WithProjectID adds the projectID to the post internal kubernetes secret params.
func (o *PostInternalKubernetesSecretParams) WithProjectID(projectID int64) *PostInternalKubernetesSecretParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the post internal kubernetes secret params.
func (o *PostInternalKubernetesSecretParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostInternalKubernetesSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param buildID
	if err := r.SetPathParam("buildID", conv.FormatInteger(o.BuildID)); err != nil {
		return err
	}

	// path param projectID
	if err := r.SetPathParam("projectID", conv.FormatInteger(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
