// Code generated by go-swagger; DO NOT EDIT.

package kubernetes

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostInternalKubernetesPodBuildIDListenReader is a Reader for the PostInternalKubernetesPodBuildIDListen structure.
type PostInternalKubernetesPodBuildIDListenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInternalKubernetesPodBuildIDListenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostInternalKubernetesPodBuildIDListenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostInternalKubernetesPodBuildIDListenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /internal/kubernetes/pod/{buildID}/listen] PostInternalKubernetesPodBuildIDListen", response, response.Code())
	}
}

// NewPostInternalKubernetesPodBuildIDListenOK creates a PostInternalKubernetesPodBuildIDListenOK with default headers values
func NewPostInternalKubernetesPodBuildIDListenOK() *PostInternalKubernetesPodBuildIDListenOK {
	return &PostInternalKubernetesPodBuildIDListenOK{}
}

/*
PostInternalKubernetesPodBuildIDListenOK describes a response with status code 200, with default header values.

OK
*/
type PostInternalKubernetesPodBuildIDListenOK struct {
}

// IsSuccess returns true when this post internal kubernetes pod build Id listen o k response has a 2xx status code
func (o *PostInternalKubernetesPodBuildIDListenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post internal kubernetes pod build Id listen o k response has a 3xx status code
func (o *PostInternalKubernetesPodBuildIDListenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post internal kubernetes pod build Id listen o k response has a 4xx status code
func (o *PostInternalKubernetesPodBuildIDListenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post internal kubernetes pod build Id listen o k response has a 5xx status code
func (o *PostInternalKubernetesPodBuildIDListenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post internal kubernetes pod build Id listen o k response a status code equal to that given
func (o *PostInternalKubernetesPodBuildIDListenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post internal kubernetes pod build Id listen o k response
func (o *PostInternalKubernetesPodBuildIDListenOK) Code() int {
	return 200
}

func (o *PostInternalKubernetesPodBuildIDListenOK) Error() string {
	return fmt.Sprintf("[POST /internal/kubernetes/pod/{buildID}/listen][%d] postInternalKubernetesPodBuildIdListenOK", 200)
}

func (o *PostInternalKubernetesPodBuildIDListenOK) String() string {
	return fmt.Sprintf("[POST /internal/kubernetes/pod/{buildID}/listen][%d] postInternalKubernetesPodBuildIdListenOK", 200)
}

func (o *PostInternalKubernetesPodBuildIDListenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInternalKubernetesPodBuildIDListenInternalServerError creates a PostInternalKubernetesPodBuildIDListenInternalServerError with default headers values
func NewPostInternalKubernetesPodBuildIDListenInternalServerError() *PostInternalKubernetesPodBuildIDListenInternalServerError {
	return &PostInternalKubernetesPodBuildIDListenInternalServerError{}
}

/*
PostInternalKubernetesPodBuildIDListenInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostInternalKubernetesPodBuildIDListenInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this post internal kubernetes pod build Id listen internal server error response has a 2xx status code
func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post internal kubernetes pod build Id listen internal server error response has a 3xx status code
func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post internal kubernetes pod build Id listen internal server error response has a 4xx status code
func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post internal kubernetes pod build Id listen internal server error response has a 5xx status code
func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post internal kubernetes pod build Id listen internal server error response a status code equal to that given
func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post internal kubernetes pod build Id listen internal server error response
func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) Code() int {
	return 500
}

func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /internal/kubernetes/pod/{buildID}/listen][%d] postInternalKubernetesPodBuildIdListenInternalServerError %s", 500, payload)
}

func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /internal/kubernetes/pod/{buildID}/listen][%d] postInternalKubernetesPodBuildIdListenInternalServerError %s", 500, payload)
}

func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostInternalKubernetesPodBuildIDListenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
