// Code generated by go-swagger; DO NOT EDIT.

package kubernetes

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewPostInternalKubernetesPodBuildIDListenParams creates a new PostInternalKubernetesPodBuildIDListenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostInternalKubernetesPodBuildIDListenParams() *PostInternalKubernetesPodBuildIDListenParams {
	return NewPostInternalKubernetesPodBuildIDListenParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostInternalKubernetesPodBuildIDListenParamsWithTimeout creates a new PostInternalKubernetesPodBuildIDListenParams object
// with the ability to set a timeout on a request.
func NewPostInternalKubernetesPodBuildIDListenParamsWithTimeout(timeout time.Duration) *PostInternalKubernetesPodBuildIDListenParams {
	return &PostInternalKubernetesPodBuildIDListenParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostInternalKubernetesPodBuildIDListenParamsWithContext creates a new PostInternalKubernetesPodBuildIDListenParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesPodBuildIDListenParams].
func NewPostInternalKubernetesPodBuildIDListenParamsWithContext(ctx context.Context) *PostInternalKubernetesPodBuildIDListenParams {
	return &PostInternalKubernetesPodBuildIDListenParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostInternalKubernetesPodBuildIDListenParamsWithHTTPClient creates a new PostInternalKubernetesPodBuildIDListenParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostInternalKubernetesPodBuildIDListenParamsWithHTTPClient(client *http.Client) *PostInternalKubernetesPodBuildIDListenParams {
	return &PostInternalKubernetesPodBuildIDListenParams{
		HTTPClient: client,
	}
}

/*
PostInternalKubernetesPodBuildIDListenParams contains all the parameters to send to the API endpoint

	for the post internal kubernetes pod build ID listen operation.

	Typically these are written to a http.Request.
*/
type PostInternalKubernetesPodBuildIDListenParams struct {

	/* BuildID.

	   Build ID
	*/
	BuildID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post internal kubernetes pod build ID listen params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInternalKubernetesPodBuildIDListenParams) WithDefaults() *PostInternalKubernetesPodBuildIDListenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post internal kubernetes pod build ID listen params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostInternalKubernetesPodBuildIDListenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post internal kubernetes pod build ID listen params.
func (o *PostInternalKubernetesPodBuildIDListenParams) WithTimeout(timeout time.Duration) *PostInternalKubernetesPodBuildIDListenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post internal kubernetes pod build ID listen params.
func (o *PostInternalKubernetesPodBuildIDListenParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post internal kubernetes pod build ID listen params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesPodBuildIDListenParams].
func (o *PostInternalKubernetesPodBuildIDListenParams) WithContext(ctx context.Context) *PostInternalKubernetesPodBuildIDListenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post internal kubernetes pod build ID listen params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostInternalKubernetesPodBuildIDListenParams].
func (o *PostInternalKubernetesPodBuildIDListenParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post internal kubernetes pod build ID listen params.
func (o *PostInternalKubernetesPodBuildIDListenParams) WithHTTPClient(client *http.Client) *PostInternalKubernetesPodBuildIDListenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post internal kubernetes pod build ID listen params.
func (o *PostInternalKubernetesPodBuildIDListenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildID adds the buildID to the post internal kubernetes pod build ID listen params.
func (o *PostInternalKubernetesPodBuildIDListenParams) WithBuildID(buildID int64) *PostInternalKubernetesPodBuildIDListenParams {
	o.SetBuildID(buildID)
	return o
}

// SetBuildID adds the buildId to the post internal kubernetes pod build ID listen params.
func (o *PostInternalKubernetesPodBuildIDListenParams) SetBuildID(buildID int64) {
	o.BuildID = buildID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostInternalKubernetesPodBuildIDListenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param buildID
	if err := r.SetPathParam("buildID", conv.FormatInteger(o.BuildID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
