// Code generated by go-swagger; DO NOT EDIT.

package environment

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteEnvEnvIDParams creates a new DeleteEnvEnvIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteEnvEnvIDParams() *DeleteEnvEnvIDParams {
	return NewDeleteEnvEnvIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteEnvEnvIDParamsWithTimeout creates a new DeleteEnvEnvIDParams object
// with the ability to set a timeout on a request.
func NewDeleteEnvEnvIDParamsWithTimeout(timeout time.Duration) *DeleteEnvEnvIDParams {
	return &DeleteEnvEnvIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteEnvEnvIDParamsWithContext creates a new DeleteEnvEnvIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteEnvEnvIDParams].
func NewDeleteEnvEnvIDParamsWithContext(ctx context.Context) *DeleteEnvEnvIDParams {
	return &DeleteEnvEnvIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteEnvEnvIDParamsWithHTTPClient creates a new DeleteEnvEnvIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteEnvEnvIDParamsWithHTTPClient(client *http.Client) *DeleteEnvEnvIDParams {
	return &DeleteEnvEnvIDParams{
		HTTPClient: client,
	}
}

/*
DeleteEnvEnvIDParams contains all the parameters to send to the API endpoint

	for the delete env env ID operation.

	Typically these are written to a http.Request.
*/
type DeleteEnvEnvIDParams struct {

	/* EnvID.

	   Environment asset ID
	*/
	EnvID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete env env ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEnvEnvIDParams) WithDefaults() *DeleteEnvEnvIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete env env ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEnvEnvIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete env env ID params.
func (o *DeleteEnvEnvIDParams) WithTimeout(timeout time.Duration) *DeleteEnvEnvIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete env env ID params.
func (o *DeleteEnvEnvIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete env env ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteEnvEnvIDParams].
func (o *DeleteEnvEnvIDParams) WithContext(ctx context.Context) *DeleteEnvEnvIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete env env ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteEnvEnvIDParams].
func (o *DeleteEnvEnvIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete env env ID params.
func (o *DeleteEnvEnvIDParams) WithHTTPClient(client *http.Client) *DeleteEnvEnvIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete env env ID params.
func (o *DeleteEnvEnvIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvID adds the envID to the delete env env ID params.
func (o *DeleteEnvEnvIDParams) WithEnvID(envID int64) *DeleteEnvEnvIDParams {
	o.SetEnvID(envID)
	return o
}

// SetEnvID adds the envId to the delete env env ID params.
func (o *DeleteEnvEnvIDParams) SetEnvID(envID int64) {
	o.EnvID = envID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteEnvEnvIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param envId
	if err := r.SetPathParam("envId", conv.FormatInteger(o.EnvID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
