// Code generated by go-swagger; DO NOT EDIT.

package environment

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetEnvParams creates a new GetEnvParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEnvParams() *GetEnvParams {
	return NewGetEnvParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetEnvParamsWithTimeout creates a new GetEnvParams object
// with the ability to set a timeout on a request.
func NewGetEnvParamsWithTimeout(timeout time.Duration) *GetEnvParams {
	return &GetEnvParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetEnvParamsWithContext creates a new GetEnvParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEnvParams].
func NewGetEnvParamsWithContext(ctx context.Context) *GetEnvParams {
	return &GetEnvParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetEnvParamsWithHTTPClient creates a new GetEnvParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEnvParamsWithHTTPClient(client *http.Client) *GetEnvParams {
	return &GetEnvParams{
		HTTPClient: client,
	}
}

/*
GetEnvParams contains all the parameters to send to the API endpoint

	for the get env operation.

	Typically these are written to a http.Request.
*/
type GetEnvParams struct {

	/* ProjectID.

	   Filter by Project ID
	*/
	ProjectID *int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get env params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnvParams) WithDefaults() *GetEnvParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get env params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnvParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get env params.
func (o *GetEnvParams) WithTimeout(timeout time.Duration) *GetEnvParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get env params.
func (o *GetEnvParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get env params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEnvParams].
func (o *GetEnvParams) WithContext(ctx context.Context) *GetEnvParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get env params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEnvParams].
func (o *GetEnvParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get env params.
func (o *GetEnvParams) WithHTTPClient(client *http.Client) *GetEnvParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get env params.
func (o *GetEnvParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get env params.
func (o *GetEnvParams) WithProjectID(projectID *int64) *GetEnvParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get env params.
func (o *GetEnvParams) SetProjectID(projectID *int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetEnvParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProjectID != nil {

		// query param project_id
		var qrProjectID int64

		if o.ProjectID != nil {
			qrProjectID = *o.ProjectID
		}
		qProjectID := conv.FormatInteger(qrProjectID)
		if qProjectID != "" {

			if err := r.SetQueryParam("project_id", qProjectID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
