// Code generated by go-swagger; DO NOT EDIT.

package environment

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetEnvEnvIDParams creates a new GetEnvEnvIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEnvEnvIDParams() *GetEnvEnvIDParams {
	return NewGetEnvEnvIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetEnvEnvIDParamsWithTimeout creates a new GetEnvEnvIDParams object
// with the ability to set a timeout on a request.
func NewGetEnvEnvIDParamsWithTimeout(timeout time.Duration) *GetEnvEnvIDParams {
	return &GetEnvEnvIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetEnvEnvIDParamsWithContext creates a new GetEnvEnvIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEnvEnvIDParams].
func NewGetEnvEnvIDParamsWithContext(ctx context.Context) *GetEnvEnvIDParams {
	return &GetEnvEnvIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetEnvEnvIDParamsWithHTTPClient creates a new GetEnvEnvIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEnvEnvIDParamsWithHTTPClient(client *http.Client) *GetEnvEnvIDParams {
	return &GetEnvEnvIDParams{
		HTTPClient: client,
	}
}

/*
GetEnvEnvIDParams contains all the parameters to send to the API endpoint

	for the get env env ID operation.

	Typically these are written to a http.Request.
*/
type GetEnvEnvIDParams struct {

	/* EnvID.

	   Environment asset ID
	*/
	EnvID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get env env ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnvEnvIDParams) WithDefaults() *GetEnvEnvIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get env env ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnvEnvIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get env env ID params.
func (o *GetEnvEnvIDParams) WithTimeout(timeout time.Duration) *GetEnvEnvIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get env env ID params.
func (o *GetEnvEnvIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get env env ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEnvEnvIDParams].
func (o *GetEnvEnvIDParams) WithContext(ctx context.Context) *GetEnvEnvIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get env env ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetEnvEnvIDParams].
func (o *GetEnvEnvIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get env env ID params.
func (o *GetEnvEnvIDParams) WithHTTPClient(client *http.Client) *GetEnvEnvIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get env env ID params.
func (o *GetEnvEnvIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvID adds the envID to the get env env ID params.
func (o *GetEnvEnvIDParams) WithEnvID(envID int64) *GetEnvEnvIDParams {
	o.SetEnvID(envID)
	return o
}

// SetEnvID adds the envId to the get env env ID params.
func (o *GetEnvEnvIDParams) SetEnvID(envID int64) {
	o.EnvID = envID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetEnvEnvIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param envId
	if err := r.SetPathParam("envId", conv.FormatInteger(o.EnvID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
