// Code generated by go-swagger; DO NOT EDIT.

package environment

import (
	"context"
	"net/http"
	"time"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostEnvParams creates a new PostEnvParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostEnvParams() *PostEnvParams {
	return NewPostEnvParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostEnvParamsWithTimeout creates a new PostEnvParams object
// with the ability to set a timeout on a request.
func NewPostEnvParamsWithTimeout(timeout time.Duration) *PostEnvParams {
	return &PostEnvParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostEnvParamsWithContext creates a new PostEnvParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostEnvParams].
func NewPostEnvParamsWithContext(ctx context.Context) *PostEnvParams {
	return &PostEnvParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostEnvParamsWithHTTPClient creates a new PostEnvParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostEnvParamsWithHTTPClient(client *http.Client) *PostEnvParams {
	return &PostEnvParams{
		HTTPClient: client,
	}
}

/*
PostEnvParams contains all the parameters to send to the API endpoint

	for the post env operation.

	Typically these are written to a http.Request.
*/
type PostEnvParams struct {

	/* Env.

	   Environment asset data
	*/
	Env *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post env params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEnvParams) WithDefaults() *PostEnvParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post env params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEnvParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post env params.
func (o *PostEnvParams) WithTimeout(timeout time.Duration) *PostEnvParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post env params.
func (o *PostEnvParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post env params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostEnvParams].
func (o *PostEnvParams) WithContext(ctx context.Context) *PostEnvParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post env params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostEnvParams].
func (o *PostEnvParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post env params.
func (o *PostEnvParams) WithHTTPClient(client *http.Client) *PostEnvParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post env params.
func (o *PostEnvParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnv adds the env to the post env params.
func (o *PostEnvParams) WithEnv(env *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) *PostEnvParams {
	o.SetEnv(env)
	return o
}

// SetEnv adds the env to the post env params.
func (o *PostEnvParams) SetEnv(env *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) {
	o.Env = env
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostEnvParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Env != nil {
		if err := r.SetBodyParam(o.Env); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
