// Code generated by go-swagger; DO NOT EDIT.

package environment

import (
	"context"
	"net/http"
	"time"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewPutEnvEnvIDParams creates a new PutEnvEnvIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutEnvEnvIDParams() *PutEnvEnvIDParams {
	return NewPutEnvEnvIDParamsWithTimeout(cr.DefaultTimeout)
}

// NewPutEnvEnvIDParamsWithTimeout creates a new PutEnvEnvIDParams object
// with the ability to set a timeout on a request.
func NewPutEnvEnvIDParamsWithTimeout(timeout time.Duration) *PutEnvEnvIDParams {
	return &PutEnvEnvIDParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPutEnvEnvIDParamsWithContext creates a new PutEnvEnvIDParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PutEnvEnvIDParams].
func NewPutEnvEnvIDParamsWithContext(ctx context.Context) *PutEnvEnvIDParams {
	return &PutEnvEnvIDParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPutEnvEnvIDParamsWithHTTPClient creates a new PutEnvEnvIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutEnvEnvIDParamsWithHTTPClient(client *http.Client) *PutEnvEnvIDParams {
	return &PutEnvEnvIDParams{
		HTTPClient: client,
	}
}

/*
PutEnvEnvIDParams contains all the parameters to send to the API endpoint

	for the put env env ID operation.

	Typically these are written to a http.Request.
*/
type PutEnvEnvIDParams struct {

	/* Env.

	   Updated environment asset data
	*/
	Env *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv

	/* EnvID.

	   Environment asset ID
	*/
	EnvID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the put env env ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutEnvEnvIDParams) WithDefaults() *PutEnvEnvIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put env env ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutEnvEnvIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put env env ID params.
func (o *PutEnvEnvIDParams) WithTimeout(timeout time.Duration) *PutEnvEnvIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put env env ID params.
func (o *PutEnvEnvIDParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the put env env ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutEnvEnvIDParams].
func (o *PutEnvEnvIDParams) WithContext(ctx context.Context) *PutEnvEnvIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put env env ID params.
//
// Deprecated: use the operation call with context to pass the context instead of [PutEnvEnvIDParams].
func (o *PutEnvEnvIDParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the put env env ID params.
func (o *PutEnvEnvIDParams) WithHTTPClient(client *http.Client) *PutEnvEnvIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put env env ID params.
func (o *PutEnvEnvIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnv adds the env to the put env env ID params.
func (o *PutEnvEnvIDParams) WithEnv(env *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) *PutEnvEnvIDParams {
	o.SetEnv(env)
	return o
}

// SetEnv adds the env to the put env env ID params.
func (o *PutEnvEnvIDParams) SetEnv(env *models.GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) {
	o.Env = env
}

// WithEnvID adds the envID to the put env env ID params.
func (o *PutEnvEnvIDParams) WithEnvID(envID int64) *PutEnvEnvIDParams {
	o.SetEnvID(envID)
	return o
}

// SetEnvID adds the envId to the put env env ID params.
func (o *PutEnvEnvIDParams) SetEnvID(envID int64) {
	o.EnvID = envID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PutEnvEnvIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Env != nil {
		if err := r.SetBodyParam(o.Env); err != nil {
			return err
		}
	}

	// path param envId
	if err := r.SetPathParam("envId", conv.FormatInteger(o.EnvID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
