// Code generated by go-swagger; DO NOT EDIT.

package config

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new config API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new config API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new config API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for config API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// DeleteProjectIDConfig delete project configuration.
	DeleteProjectIDConfig(params *DeleteProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectIDConfigOK, error)

	// DeleteProjectIDConfigContext delete project configuration.
	DeleteProjectIDConfigContext(ctx context.Context, params *DeleteProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectIDConfigOK, error)

	// GetProjectIDConfig get project configuration.
	GetProjectIDConfig(params *GetProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectIDConfigOK, error)

	// GetProjectIDConfigContext get project configuration.
	GetProjectIDConfigContext(ctx context.Context, params *GetProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectIDConfigOK, error)

	// PostProjectIDConfig update project configuration.
	PostProjectIDConfig(params *PostProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectIDConfigOK, error)

	// PostProjectIDConfigContext update project configuration.
	PostProjectIDConfigContext(ctx context.Context, params *PostProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectIDConfigOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
DeleteProjectIDConfigdeletes project configuration.

Delete or reset the configuration for a specific project.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.DeleteProjectIDConfigContext] instead.
*/
func (a *Client) DeleteProjectIDConfig(params *DeleteProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectIDConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteProjectIDConfigContext(ctx, params, authInfo, opts...)
}

/*
DeleteProjectIDConfigContextdeletes project configuration.

Delete or reset the configuration for a specific project.

Do not use the deprecated [DeleteProjectIDConfigParams.Context] with this method: it would be ignored.
*/
func (a *Client) DeleteProjectIDConfigContext(ctx context.Context, params *DeleteProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProjectIDConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteProjectIDConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectIDConfig",
		Method:             "DELETE",
		PathPattern:        "/project/{id}/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteProjectIDConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteProjectIDConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectIDConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectIDConfiggets project configuration.

Get the configuration for a specific project.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectIDConfigContext] instead.
*/
func (a *Client) GetProjectIDConfig(params *GetProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectIDConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectIDConfigContext(ctx, params, authInfo, opts...)
}

/*
GetProjectIDConfigContextgets project configuration.

Get the configuration for a specific project.

Do not use the deprecated [GetProjectIDConfigParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectIDConfigContext(ctx context.Context, params *GetProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectIDConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectIDConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectIDConfig",
		Method:             "GET",
		PathPattern:        "/project/{id}/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProjectIDConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectIDConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectIDConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostProjectIDConfigupdates project configuration.

Create or update the configuration for a specific project (Supports partial updates).

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostProjectIDConfigContext] instead.
*/
func (a *Client) PostProjectIDConfig(params *PostProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectIDConfigOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostProjectIDConfigContext(ctx, params, authInfo, opts...)
}

/*
PostProjectIDConfigContextupdates project configuration.

Create or update the configuration for a specific project (Supports partial updates).

Do not use the deprecated [PostProjectIDConfigParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostProjectIDConfigContext(ctx context.Context, params *PostProjectIDConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostProjectIDConfigOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProjectIDConfigParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostProjectIDConfig",
		Method:             "POST",
		PathPattern:        "/project/{id}/config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostProjectIDConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProjectIDConfigOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostProjectIDConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [ConfigParams].
	ctx context.Context
}
