// Code generated by go-swagger; DO NOT EDIT.

package config

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteProjectIDConfigParams creates a new DeleteProjectIDConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectIDConfigParams() *DeleteProjectIDConfigParams {
	return NewDeleteProjectIDConfigParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteProjectIDConfigParamsWithTimeout creates a new DeleteProjectIDConfigParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectIDConfigParamsWithTimeout(timeout time.Duration) *DeleteProjectIDConfigParams {
	return &DeleteProjectIDConfigParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteProjectIDConfigParamsWithContext creates a new DeleteProjectIDConfigParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectIDConfigParams].
func NewDeleteProjectIDConfigParamsWithContext(ctx context.Context) *DeleteProjectIDConfigParams {
	return &DeleteProjectIDConfigParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteProjectIDConfigParamsWithHTTPClient creates a new DeleteProjectIDConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectIDConfigParamsWithHTTPClient(client *http.Client) *DeleteProjectIDConfigParams {
	return &DeleteProjectIDConfigParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectIDConfigParams contains all the parameters to send to the API endpoint

	for the delete project ID config operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectIDConfigParams struct {

	/* ID.

	   Project ID
	*/
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete project ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectIDConfigParams) WithDefaults() *DeleteProjectIDConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectIDConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project ID config params.
func (o *DeleteProjectIDConfigParams) WithTimeout(timeout time.Duration) *DeleteProjectIDConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project ID config params.
func (o *DeleteProjectIDConfigParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete project ID config params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectIDConfigParams].
func (o *DeleteProjectIDConfigParams) WithContext(ctx context.Context) *DeleteProjectIDConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project ID config params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectIDConfigParams].
func (o *DeleteProjectIDConfigParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project ID config params.
func (o *DeleteProjectIDConfigParams) WithHTTPClient(client *http.Client) *DeleteProjectIDConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project ID config params.
func (o *DeleteProjectIDConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete project ID config params.
func (o *DeleteProjectIDConfigParams) WithID(id int64) *DeleteProjectIDConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete project ID config params.
func (o *DeleteProjectIDConfigParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteProjectIDConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
