// Code generated by go-swagger; DO NOT EDIT.

package config

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteProjectIDConfigReader is a Reader for the DeleteProjectIDConfig structure.
type DeleteProjectIDConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProjectIDConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteProjectIDConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteProjectIDConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteProjectIDConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteProjectIDConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /project/{id}/config] DeleteProjectIDConfig", response, response.Code())
	}
}

// NewDeleteProjectIDConfigOK creates a DeleteProjectIDConfigOK with default headers values
func NewDeleteProjectIDConfigOK() *DeleteProjectIDConfigOK {
	return &DeleteProjectIDConfigOK{}
}

/*
DeleteProjectIDConfigOK describes a response with status code 200, with default header values.

OK
*/
type DeleteProjectIDConfigOK struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete project Id config o k response has a 2xx status code
func (o *DeleteProjectIDConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete project Id config o k response has a 3xx status code
func (o *DeleteProjectIDConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id config o k response has a 4xx status code
func (o *DeleteProjectIDConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete project Id config o k response has a 5xx status code
func (o *DeleteProjectIDConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project Id config o k response a status code equal to that given
func (o *DeleteProjectIDConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete project Id config o k response
func (o *DeleteProjectIDConfigOK) Code() int {
	return 200
}

func (o *DeleteProjectIDConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/config][%d] deleteProjectIdConfigOK %s", 200, payload)
}

func (o *DeleteProjectIDConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/config][%d] deleteProjectIdConfigOK %s", 200, payload)
}

func (o *DeleteProjectIDConfigOK) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteProjectIDConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteProjectIDConfigUnauthorized creates a DeleteProjectIDConfigUnauthorized with default headers values
func NewDeleteProjectIDConfigUnauthorized() *DeleteProjectIDConfigUnauthorized {
	return &DeleteProjectIDConfigUnauthorized{}
}

/*
DeleteProjectIDConfigUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteProjectIDConfigUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete project Id config unauthorized response has a 2xx status code
func (o *DeleteProjectIDConfigUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete project Id config unauthorized response has a 3xx status code
func (o *DeleteProjectIDConfigUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id config unauthorized response has a 4xx status code
func (o *DeleteProjectIDConfigUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete project Id config unauthorized response has a 5xx status code
func (o *DeleteProjectIDConfigUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project Id config unauthorized response a status code equal to that given
func (o *DeleteProjectIDConfigUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete project Id config unauthorized response
func (o *DeleteProjectIDConfigUnauthorized) Code() int {
	return 401
}

func (o *DeleteProjectIDConfigUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/config][%d] deleteProjectIdConfigUnauthorized %s", 401, payload)
}

func (o *DeleteProjectIDConfigUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/config][%d] deleteProjectIdConfigUnauthorized %s", 401, payload)
}

func (o *DeleteProjectIDConfigUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteProjectIDConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteProjectIDConfigNotFound creates a DeleteProjectIDConfigNotFound with default headers values
func NewDeleteProjectIDConfigNotFound() *DeleteProjectIDConfigNotFound {
	return &DeleteProjectIDConfigNotFound{}
}

/*
DeleteProjectIDConfigNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteProjectIDConfigNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete project Id config not found response has a 2xx status code
func (o *DeleteProjectIDConfigNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete project Id config not found response has a 3xx status code
func (o *DeleteProjectIDConfigNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id config not found response has a 4xx status code
func (o *DeleteProjectIDConfigNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete project Id config not found response has a 5xx status code
func (o *DeleteProjectIDConfigNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project Id config not found response a status code equal to that given
func (o *DeleteProjectIDConfigNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete project Id config not found response
func (o *DeleteProjectIDConfigNotFound) Code() int {
	return 404
}

func (o *DeleteProjectIDConfigNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/config][%d] deleteProjectIdConfigNotFound %s", 404, payload)
}

func (o *DeleteProjectIDConfigNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/config][%d] deleteProjectIdConfigNotFound %s", 404, payload)
}

func (o *DeleteProjectIDConfigNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteProjectIDConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteProjectIDConfigInternalServerError creates a DeleteProjectIDConfigInternalServerError with default headers values
func NewDeleteProjectIDConfigInternalServerError() *DeleteProjectIDConfigInternalServerError {
	return &DeleteProjectIDConfigInternalServerError{}
}

/*
DeleteProjectIDConfigInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteProjectIDConfigInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete project Id config internal server error response has a 2xx status code
func (o *DeleteProjectIDConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete project Id config internal server error response has a 3xx status code
func (o *DeleteProjectIDConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id config internal server error response has a 4xx status code
func (o *DeleteProjectIDConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete project Id config internal server error response has a 5xx status code
func (o *DeleteProjectIDConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete project Id config internal server error response a status code equal to that given
func (o *DeleteProjectIDConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete project Id config internal server error response
func (o *DeleteProjectIDConfigInternalServerError) Code() int {
	return 500
}

func (o *DeleteProjectIDConfigInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/config][%d] deleteProjectIdConfigInternalServerError %s", 500, payload)
}

func (o *DeleteProjectIDConfigInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/config][%d] deleteProjectIdConfigInternalServerError %s", 500, payload)
}

func (o *DeleteProjectIDConfigInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteProjectIDConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
