// Code generated by go-swagger; DO NOT EDIT.

package google_play_credentials

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteGooglePlayCredentialsCredentialsIDReader is a Reader for the DeleteGooglePlayCredentialsCredentialsID structure.
type DeleteGooglePlayCredentialsCredentialsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGooglePlayCredentialsCredentialsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteGooglePlayCredentialsCredentialsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteGooglePlayCredentialsCredentialsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteGooglePlayCredentialsCredentialsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteGooglePlayCredentialsCredentialsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /google-play-credentials/{credentialsId}] DeleteGooglePlayCredentialsCredentialsID", response, response.Code())
	}
}

// NewDeleteGooglePlayCredentialsCredentialsIDOK creates a DeleteGooglePlayCredentialsCredentialsIDOK with default headers values
func NewDeleteGooglePlayCredentialsCredentialsIDOK() *DeleteGooglePlayCredentialsCredentialsIDOK {
	return &DeleteGooglePlayCredentialsCredentialsIDOK{}
}

/*
DeleteGooglePlayCredentialsCredentialsIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteGooglePlayCredentialsCredentialsIDOK struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete google play credentials credentials Id o k response has a 2xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete google play credentials credentials Id o k response has a 3xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete google play credentials credentials Id o k response has a 4xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete google play credentials credentials Id o k response has a 5xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete google play credentials credentials Id o k response a status code equal to that given
func (o *DeleteGooglePlayCredentialsCredentialsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete google play credentials credentials Id o k response
func (o *DeleteGooglePlayCredentialsCredentialsIDOK) Code() int {
	return 200
}

func (o *DeleteGooglePlayCredentialsCredentialsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /google-play-credentials/{credentialsId}][%d] deleteGooglePlayCredentialsCredentialsIdOK %s", 200, payload)
}

func (o *DeleteGooglePlayCredentialsCredentialsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /google-play-credentials/{credentialsId}][%d] deleteGooglePlayCredentialsCredentialsIdOK %s", 200, payload)
}

func (o *DeleteGooglePlayCredentialsCredentialsIDOK) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteGooglePlayCredentialsCredentialsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteGooglePlayCredentialsCredentialsIDUnauthorized creates a DeleteGooglePlayCredentialsCredentialsIDUnauthorized with default headers values
func NewDeleteGooglePlayCredentialsCredentialsIDUnauthorized() *DeleteGooglePlayCredentialsCredentialsIDUnauthorized {
	return &DeleteGooglePlayCredentialsCredentialsIDUnauthorized{}
}

/*
DeleteGooglePlayCredentialsCredentialsIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteGooglePlayCredentialsCredentialsIDUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete google play credentials credentials Id unauthorized response has a 2xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete google play credentials credentials Id unauthorized response has a 3xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete google play credentials credentials Id unauthorized response has a 4xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete google play credentials credentials Id unauthorized response has a 5xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete google play credentials credentials Id unauthorized response a status code equal to that given
func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete google play credentials credentials Id unauthorized response
func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /google-play-credentials/{credentialsId}][%d] deleteGooglePlayCredentialsCredentialsIdUnauthorized %s", 401, payload)
}

func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /google-play-credentials/{credentialsId}][%d] deleteGooglePlayCredentialsCredentialsIdUnauthorized %s", 401, payload)
}

func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteGooglePlayCredentialsCredentialsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteGooglePlayCredentialsCredentialsIDNotFound creates a DeleteGooglePlayCredentialsCredentialsIDNotFound with default headers values
func NewDeleteGooglePlayCredentialsCredentialsIDNotFound() *DeleteGooglePlayCredentialsCredentialsIDNotFound {
	return &DeleteGooglePlayCredentialsCredentialsIDNotFound{}
}

/*
DeleteGooglePlayCredentialsCredentialsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteGooglePlayCredentialsCredentialsIDNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete google play credentials credentials Id not found response has a 2xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete google play credentials credentials Id not found response has a 3xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete google play credentials credentials Id not found response has a 4xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete google play credentials credentials Id not found response has a 5xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete google play credentials credentials Id not found response a status code equal to that given
func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete google play credentials credentials Id not found response
func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) Code() int {
	return 404
}

func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /google-play-credentials/{credentialsId}][%d] deleteGooglePlayCredentialsCredentialsIdNotFound %s", 404, payload)
}

func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /google-play-credentials/{credentialsId}][%d] deleteGooglePlayCredentialsCredentialsIdNotFound %s", 404, payload)
}

func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteGooglePlayCredentialsCredentialsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteGooglePlayCredentialsCredentialsIDInternalServerError creates a DeleteGooglePlayCredentialsCredentialsIDInternalServerError with default headers values
func NewDeleteGooglePlayCredentialsCredentialsIDInternalServerError() *DeleteGooglePlayCredentialsCredentialsIDInternalServerError {
	return &DeleteGooglePlayCredentialsCredentialsIDInternalServerError{}
}

/*
DeleteGooglePlayCredentialsCredentialsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteGooglePlayCredentialsCredentialsIDInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete google play credentials credentials Id internal server error response has a 2xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete google play credentials credentials Id internal server error response has a 3xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete google play credentials credentials Id internal server error response has a 4xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete google play credentials credentials Id internal server error response has a 5xx status code
func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete google play credentials credentials Id internal server error response a status code equal to that given
func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete google play credentials credentials Id internal server error response
func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /google-play-credentials/{credentialsId}][%d] deleteGooglePlayCredentialsCredentialsIdInternalServerError %s", 500, payload)
}

func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /google-play-credentials/{credentialsId}][%d] deleteGooglePlayCredentialsCredentialsIdInternalServerError %s", 500, payload)
}

func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteGooglePlayCredentialsCredentialsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
