// Code generated by go-swagger; DO NOT EDIT.

package google_play_credentials

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGooglePlayCredentialsParams creates a new GetGooglePlayCredentialsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGooglePlayCredentialsParams() *GetGooglePlayCredentialsParams {
	return NewGetGooglePlayCredentialsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetGooglePlayCredentialsParamsWithTimeout creates a new GetGooglePlayCredentialsParams object
// with the ability to set a timeout on a request.
func NewGetGooglePlayCredentialsParamsWithTimeout(timeout time.Duration) *GetGooglePlayCredentialsParams {
	return &GetGooglePlayCredentialsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetGooglePlayCredentialsParamsWithContext creates a new GetGooglePlayCredentialsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGooglePlayCredentialsParams].
func NewGetGooglePlayCredentialsParamsWithContext(ctx context.Context) *GetGooglePlayCredentialsParams {
	return &GetGooglePlayCredentialsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetGooglePlayCredentialsParamsWithHTTPClient creates a new GetGooglePlayCredentialsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGooglePlayCredentialsParamsWithHTTPClient(client *http.Client) *GetGooglePlayCredentialsParams {
	return &GetGooglePlayCredentialsParams{
		HTTPClient: client,
	}
}

/*
GetGooglePlayCredentialsParams contains all the parameters to send to the API endpoint

	for the get google play credentials operation.

	Typically these are written to a http.Request.
*/
type GetGooglePlayCredentialsParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get google play credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGooglePlayCredentialsParams) WithDefaults() *GetGooglePlayCredentialsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get google play credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGooglePlayCredentialsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get google play credentials params.
func (o *GetGooglePlayCredentialsParams) WithTimeout(timeout time.Duration) *GetGooglePlayCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get google play credentials params.
func (o *GetGooglePlayCredentialsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get google play credentials params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGooglePlayCredentialsParams].
func (o *GetGooglePlayCredentialsParams) WithContext(ctx context.Context) *GetGooglePlayCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get google play credentials params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetGooglePlayCredentialsParams].
func (o *GetGooglePlayCredentialsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get google play credentials params.
func (o *GetGooglePlayCredentialsParams) WithHTTPClient(client *http.Client) *GetGooglePlayCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get google play credentials params.
func (o *GetGooglePlayCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetGooglePlayCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
