// Code generated by go-swagger; DO NOT EDIT.

package google_play_credentials

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostGooglePlayCredentialsReader is a Reader for the PostGooglePlayCredentials structure.
type PostGooglePlayCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGooglePlayCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostGooglePlayCredentialsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostGooglePlayCredentialsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostGooglePlayCredentialsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /google-play-credentials] PostGooglePlayCredentials", response, response.Code())
	}
}

// NewPostGooglePlayCredentialsCreated creates a PostGooglePlayCredentialsCreated with default headers values
func NewPostGooglePlayCredentialsCreated() *PostGooglePlayCredentialsCreated {
	return &PostGooglePlayCredentialsCreated{}
}

/*
PostGooglePlayCredentialsCreated describes a response with status code 201, with default header values.

Created
*/
type PostGooglePlayCredentialsCreated struct {
	Payload any
}

// IsSuccess returns true when this post google play credentials created response has a 2xx status code
func (o *PostGooglePlayCredentialsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post google play credentials created response has a 3xx status code
func (o *PostGooglePlayCredentialsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post google play credentials created response has a 4xx status code
func (o *PostGooglePlayCredentialsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post google play credentials created response has a 5xx status code
func (o *PostGooglePlayCredentialsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post google play credentials created response a status code equal to that given
func (o *PostGooglePlayCredentialsCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post google play credentials created response
func (o *PostGooglePlayCredentialsCreated) Code() int {
	return 201
}

func (o *PostGooglePlayCredentialsCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /google-play-credentials][%d] postGooglePlayCredentialsCreated %s", 201, payload)
}

func (o *PostGooglePlayCredentialsCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /google-play-credentials][%d] postGooglePlayCredentialsCreated %s", 201, payload)
}

func (o *PostGooglePlayCredentialsCreated) GetPayload() any {
	return o.Payload
}

func (o *PostGooglePlayCredentialsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostGooglePlayCredentialsUnauthorized creates a PostGooglePlayCredentialsUnauthorized with default headers values
func NewPostGooglePlayCredentialsUnauthorized() *PostGooglePlayCredentialsUnauthorized {
	return &PostGooglePlayCredentialsUnauthorized{}
}

/*
PostGooglePlayCredentialsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostGooglePlayCredentialsUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this post google play credentials unauthorized response has a 2xx status code
func (o *PostGooglePlayCredentialsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post google play credentials unauthorized response has a 3xx status code
func (o *PostGooglePlayCredentialsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post google play credentials unauthorized response has a 4xx status code
func (o *PostGooglePlayCredentialsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post google play credentials unauthorized response has a 5xx status code
func (o *PostGooglePlayCredentialsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post google play credentials unauthorized response a status code equal to that given
func (o *PostGooglePlayCredentialsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post google play credentials unauthorized response
func (o *PostGooglePlayCredentialsUnauthorized) Code() int {
	return 401
}

func (o *PostGooglePlayCredentialsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /google-play-credentials][%d] postGooglePlayCredentialsUnauthorized %s", 401, payload)
}

func (o *PostGooglePlayCredentialsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /google-play-credentials][%d] postGooglePlayCredentialsUnauthorized %s", 401, payload)
}

func (o *PostGooglePlayCredentialsUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostGooglePlayCredentialsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostGooglePlayCredentialsInternalServerError creates a PostGooglePlayCredentialsInternalServerError with default headers values
func NewPostGooglePlayCredentialsInternalServerError() *PostGooglePlayCredentialsInternalServerError {
	return &PostGooglePlayCredentialsInternalServerError{}
}

/*
PostGooglePlayCredentialsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostGooglePlayCredentialsInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this post google play credentials internal server error response has a 2xx status code
func (o *PostGooglePlayCredentialsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post google play credentials internal server error response has a 3xx status code
func (o *PostGooglePlayCredentialsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post google play credentials internal server error response has a 4xx status code
func (o *PostGooglePlayCredentialsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post google play credentials internal server error response has a 5xx status code
func (o *PostGooglePlayCredentialsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post google play credentials internal server error response a status code equal to that given
func (o *PostGooglePlayCredentialsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post google play credentials internal server error response
func (o *PostGooglePlayCredentialsInternalServerError) Code() int {
	return 500
}

func (o *PostGooglePlayCredentialsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /google-play-credentials][%d] postGooglePlayCredentialsInternalServerError %s", 500, payload)
}

func (o *PostGooglePlayCredentialsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /google-play-credentials][%d] postGooglePlayCredentialsInternalServerError %s", 500, payload)
}

func (o *PostGooglePlayCredentialsInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostGooglePlayCredentialsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
