// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new builds API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new builds API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new builds API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for builds API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// DeleteProjectIDBuildBuildID delete a build.
	DeleteProjectIDBuildBuildID(params *DeleteProjectIDBuildBuildIDParams, opts ...ClientOption) (*DeleteProjectIDBuildBuildIDOK, error)

	// DeleteProjectIDBuildBuildIDContext delete a build.
	DeleteProjectIDBuildBuildIDContext(ctx context.Context, params *DeleteProjectIDBuildBuildIDParams, opts ...ClientOption) (*DeleteProjectIDBuildBuildIDOK, error)

	// DeleteProjectIDCache purge build cache.
	DeleteProjectIDCache(params *DeleteProjectIDCacheParams, opts ...ClientOption) (*DeleteProjectIDCacheOK, error)

	// DeleteProjectIDCacheContext purge build cache.
	DeleteProjectIDCacheContext(ctx context.Context, params *DeleteProjectIDCacheParams, opts ...ClientOption) (*DeleteProjectIDCacheOK, error)

	// GetProjectIDBuildBuildIDDownload download build artifact.
	GetProjectIDBuildBuildIDDownload(params *GetProjectIDBuildBuildIDDownloadParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDDownloadOK, error)

	// GetProjectIDBuildBuildIDDownloadContext download build artifact.
	GetProjectIDBuildBuildIDDownloadContext(ctx context.Context, params *GetProjectIDBuildBuildIDDownloadParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDDownloadOK, error)

	// GetProjectIDBuildBuildIDLogs get build logs.
	GetProjectIDBuildBuildIDLogs(params *GetProjectIDBuildBuildIDLogsParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDLogsOK, error)

	// GetProjectIDBuildBuildIDLogsContext get build logs.
	GetProjectIDBuildBuildIDLogsContext(ctx context.Context, params *GetProjectIDBuildBuildIDLogsParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDLogsOK, error)

	// GetProjectIDBuildBuildIDLogsSync get build logs via HTTP polling.
	GetProjectIDBuildBuildIDLogsSync(params *GetProjectIDBuildBuildIDLogsSyncParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDLogsSyncOK, error)

	// GetProjectIDBuildBuildIDLogsSyncContext get build logs via HTTP polling.
	GetProjectIDBuildBuildIDLogsSyncContext(ctx context.Context, params *GetProjectIDBuildBuildIDLogsSyncParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDLogsSyncOK, error)

	// GetProjectIDBuilds list builds.
	GetProjectIDBuilds(params *GetProjectIDBuildsParams, opts ...ClientOption) (*GetProjectIDBuildsOK, error)

	// GetProjectIDBuildsContext list builds.
	GetProjectIDBuildsContext(ctx context.Context, params *GetProjectIDBuildsParams, opts ...ClientOption) (*GetProjectIDBuildsOK, error)

	// GetProjectIDCacheEntries cache entries.
	GetProjectIDCacheEntries(params *GetProjectIDCacheEntriesParams, opts ...ClientOption) (*GetProjectIDCacheEntriesOK, error)

	// GetProjectIDCacheEntriesContext cache entries.
	GetProjectIDCacheEntriesContext(ctx context.Context, params *GetProjectIDCacheEntriesParams, opts ...ClientOption) (*GetProjectIDCacheEntriesOK, error)

	// GetProjectIDCacheMetrics cache metrics.
	GetProjectIDCacheMetrics(params *GetProjectIDCacheMetricsParams, opts ...ClientOption) (*GetProjectIDCacheMetricsOK, error)

	// GetProjectIDCacheMetricsContext cache metrics.
	GetProjectIDCacheMetricsContext(ctx context.Context, params *GetProjectIDCacheMetricsParams, opts ...ClientOption) (*GetProjectIDCacheMetricsOK, error)

	// PostProjectIDBuild build a project.
	PostProjectIDBuild(params *PostProjectIDBuildParams, opts ...ClientOption) (*PostProjectIDBuildOK, error)

	// PostProjectIDBuildContext build a project.
	PostProjectIDBuildContext(ctx context.Context, params *PostProjectIDBuildParams, opts ...ClientOption) (*PostProjectIDBuildOK, error)

	// PutProjectIDBuildBuildIDCancel cancel a build.
	PutProjectIDBuildBuildIDCancel(params *PutProjectIDBuildBuildIDCancelParams, opts ...ClientOption) (*PutProjectIDBuildBuildIDCancelOK, error)

	// PutProjectIDBuildBuildIDCancelContext cancel a build.
	PutProjectIDBuildBuildIDCancelContext(ctx context.Context, params *PutProjectIDBuildBuildIDCancelParams, opts ...ClientOption) (*PutProjectIDBuildBuildIDCancelOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
DeleteProjectIDBuildBuildIDdeletes a build.

Delete a specific build for a project, including its S3 artifacts and Kubernetes pod.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.DeleteProjectIDBuildBuildIDContext] instead.
*/
func (a *Client) DeleteProjectIDBuildBuildID(params *DeleteProjectIDBuildBuildIDParams, opts ...ClientOption) (*DeleteProjectIDBuildBuildIDOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteProjectIDBuildBuildIDContext(ctx, params, opts...)
}

/*
DeleteProjectIDBuildBuildIDContextdeletes a build.

Delete a specific build for a project, including its S3 artifacts and Kubernetes pod.

Do not use the deprecated [DeleteProjectIDBuildBuildIDParams.Context] with this method: it would be ignored.
*/
func (a *Client) DeleteProjectIDBuildBuildIDContext(ctx context.Context, params *DeleteProjectIDBuildBuildIDParams, opts ...ClientOption) (*DeleteProjectIDBuildBuildIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteProjectIDBuildBuildIDParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectIDBuildBuildID",
		Method:             "DELETE",
		PathPattern:        "/project/{id}/build/{buildId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteProjectIDBuildBuildIDReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteProjectIDBuildBuildIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectIDBuildBuildID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteProjectIDCachepurges build cache.

Purge cache objects for a project, optionally filtered by branch.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.DeleteProjectIDCacheContext] instead.
*/
func (a *Client) DeleteProjectIDCache(params *DeleteProjectIDCacheParams, opts ...ClientOption) (*DeleteProjectIDCacheOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteProjectIDCacheContext(ctx, params, opts...)
}

/*
DeleteProjectIDCacheContextpurges build cache.

Purge cache objects for a project, optionally filtered by branch.

Do not use the deprecated [DeleteProjectIDCacheParams.Context] with this method: it would be ignored.
*/
func (a *Client) DeleteProjectIDCacheContext(ctx context.Context, params *DeleteProjectIDCacheParams, opts ...ClientOption) (*DeleteProjectIDCacheOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteProjectIDCacheParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "DeleteProjectIDCache",
		Method:             "DELETE",
		PathPattern:        "/project/{id}/cache",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteProjectIDCacheReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteProjectIDCacheOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteProjectIDCache: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectIDBuildBuildIDDownloaddownloads build artifact.

Get a presigned URL to download the artifact for a specific build.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectIDBuildBuildIDDownloadContext] instead.
*/
func (a *Client) GetProjectIDBuildBuildIDDownload(params *GetProjectIDBuildBuildIDDownloadParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDDownloadOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectIDBuildBuildIDDownloadContext(ctx, params, opts...)
}

/*
GetProjectIDBuildBuildIDDownloadContextdownloads build artifact.

Get a presigned URL to download the artifact for a specific build.

Do not use the deprecated [GetProjectIDBuildBuildIDDownloadParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectIDBuildBuildIDDownloadContext(ctx context.Context, params *GetProjectIDBuildBuildIDDownloadParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDDownloadOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectIDBuildBuildIDDownloadParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectIDBuildBuildIDDownload",
		Method:             "GET",
		PathPattern:        "/project/{id}/build/{buildId}/download",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProjectIDBuildBuildIDDownloadReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectIDBuildBuildIDDownloadOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectIDBuildBuildIDDownload: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectIDBuildBuildIDLogsgets build logs.

Get logs for a specific build.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectIDBuildBuildIDLogsContext] instead.
*/
func (a *Client) GetProjectIDBuildBuildIDLogs(params *GetProjectIDBuildBuildIDLogsParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDLogsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectIDBuildBuildIDLogsContext(ctx, params, opts...)
}

/*
GetProjectIDBuildBuildIDLogsContextgets build logs.

Get logs for a specific build.

Do not use the deprecated [GetProjectIDBuildBuildIDLogsParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectIDBuildBuildIDLogsContext(ctx context.Context, params *GetProjectIDBuildBuildIDLogsParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDLogsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectIDBuildBuildIDLogsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectIDBuildBuildIDLogs",
		Method:             "GET",
		PathPattern:        "/project/{id}/build/{buildId}/logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProjectIDBuildBuildIDLogsReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectIDBuildBuildIDLogsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectIDBuildBuildIDLogs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectIDBuildBuildIDLogsSyncgets build logs via HTTP polling.

Fetch new logs for a specific build using HTTP long polling (10s timeout).

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectIDBuildBuildIDLogsSyncContext] instead.
*/
func (a *Client) GetProjectIDBuildBuildIDLogsSync(params *GetProjectIDBuildBuildIDLogsSyncParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDLogsSyncOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectIDBuildBuildIDLogsSyncContext(ctx, params, opts...)
}

/*
GetProjectIDBuildBuildIDLogsSyncContextgets build logs via HTTP polling.

Fetch new logs for a specific build using HTTP long polling (10s timeout).

Do not use the deprecated [GetProjectIDBuildBuildIDLogsSyncParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectIDBuildBuildIDLogsSyncContext(ctx context.Context, params *GetProjectIDBuildBuildIDLogsSyncParams, opts ...ClientOption) (*GetProjectIDBuildBuildIDLogsSyncOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectIDBuildBuildIDLogsSyncParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectIDBuildBuildIDLogsSync",
		Method:             "GET",
		PathPattern:        "/project/{id}/build/{buildId}/logs/sync",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProjectIDBuildBuildIDLogsSyncReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectIDBuildBuildIDLogsSyncOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectIDBuildBuildIDLogsSync: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectIDBuildslists builds.

Get all builds for a specific project.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectIDBuildsContext] instead.
*/
func (a *Client) GetProjectIDBuilds(params *GetProjectIDBuildsParams, opts ...ClientOption) (*GetProjectIDBuildsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectIDBuildsContext(ctx, params, opts...)
}

/*
GetProjectIDBuildsContextlists builds.

Get all builds for a specific project.

Do not use the deprecated [GetProjectIDBuildsParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectIDBuildsContext(ctx context.Context, params *GetProjectIDBuildsParams, opts ...ClientOption) (*GetProjectIDBuildsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectIDBuildsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectIDBuilds",
		Method:             "GET",
		PathPattern:        "/project/{id}/builds",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProjectIDBuildsReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectIDBuildsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectIDBuilds: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectIDCacheEntriescaches entries.

List cache fingerprints for a project branch.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectIDCacheEntriesContext] instead.
*/
func (a *Client) GetProjectIDCacheEntries(params *GetProjectIDCacheEntriesParams, opts ...ClientOption) (*GetProjectIDCacheEntriesOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectIDCacheEntriesContext(ctx, params, opts...)
}

/*
GetProjectIDCacheEntriesContextcaches entries.

List cache fingerprints for a project branch.

Do not use the deprecated [GetProjectIDCacheEntriesParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectIDCacheEntriesContext(ctx context.Context, params *GetProjectIDCacheEntriesParams, opts ...ClientOption) (*GetProjectIDCacheEntriesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectIDCacheEntriesParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectIDCacheEntries",
		Method:             "GET",
		PathPattern:        "/project/{id}/cache/entries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProjectIDCacheEntriesReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectIDCacheEntriesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectIDCacheEntries: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetProjectIDCacheMetricscaches metrics.

Get cache metrics for a project, optionally filtered by branch.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetProjectIDCacheMetricsContext] instead.
*/
func (a *Client) GetProjectIDCacheMetrics(params *GetProjectIDCacheMetricsParams, opts ...ClientOption) (*GetProjectIDCacheMetricsOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetProjectIDCacheMetricsContext(ctx, params, opts...)
}

/*
GetProjectIDCacheMetricsContextcaches metrics.

Get cache metrics for a project, optionally filtered by branch.

Do not use the deprecated [GetProjectIDCacheMetricsParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetProjectIDCacheMetricsContext(ctx context.Context, params *GetProjectIDCacheMetricsParams, opts ...ClientOption) (*GetProjectIDCacheMetricsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetProjectIDCacheMetricsParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "GetProjectIDCacheMetrics",
		Method:             "GET",
		PathPattern:        "/project/{id}/cache/metrics",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProjectIDCacheMetricsReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetProjectIDCacheMetricsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectIDCacheMetrics: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostProjectIDBuildbuilds a project.

Start a build for a specific project.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostProjectIDBuildContext] instead.
*/
func (a *Client) PostProjectIDBuild(params *PostProjectIDBuildParams, opts ...ClientOption) (*PostProjectIDBuildOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostProjectIDBuildContext(ctx, params, opts...)
}

/*
PostProjectIDBuildContextbuilds a project.

Start a build for a specific project.

Do not use the deprecated [PostProjectIDBuildParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostProjectIDBuildContext(ctx context.Context, params *PostProjectIDBuildParams, opts ...ClientOption) (*PostProjectIDBuildOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostProjectIDBuildParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostProjectIDBuild",
		Method:             "POST",
		PathPattern:        "/project/{id}/build",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostProjectIDBuildReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostProjectIDBuildOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostProjectIDBuild: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutProjectIDBuildBuildIDCancelcancels a build.

Cancel a specific build for a project.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PutProjectIDBuildBuildIDCancelContext] instead.
*/
func (a *Client) PutProjectIDBuildBuildIDCancel(params *PutProjectIDBuildBuildIDCancelParams, opts ...ClientOption) (*PutProjectIDBuildBuildIDCancelOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PutProjectIDBuildBuildIDCancelContext(ctx, params, opts...)
}

/*
PutProjectIDBuildBuildIDCancelContextcancels a build.

Cancel a specific build for a project.

Do not use the deprecated [PutProjectIDBuildBuildIDCancelParams.Context] with this method: it would be ignored.
*/
func (a *Client) PutProjectIDBuildBuildIDCancelContext(ctx context.Context, params *PutProjectIDBuildBuildIDCancelParams, opts ...ClientOption) (*PutProjectIDBuildBuildIDCancelOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutProjectIDBuildBuildIDCancelParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PutProjectIDBuildBuildIDCancel",
		Method:             "PUT",
		PathPattern:        "/project/{id}/build/{buildId}/cancel",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutProjectIDBuildBuildIDCancelReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutProjectIDBuildBuildIDCancelOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutProjectIDBuildBuildIDCancel: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [BuildsParams].
	ctx context.Context
}
