// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteProjectIDBuildBuildIDReader is a Reader for the DeleteProjectIDBuildBuildID structure.
type DeleteProjectIDBuildBuildIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProjectIDBuildBuildIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteProjectIDBuildBuildIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteProjectIDBuildBuildIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteProjectIDBuildBuildIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteProjectIDBuildBuildIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteProjectIDBuildBuildIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /project/{id}/build/{buildId}] DeleteProjectIDBuildBuildID", response, response.Code())
	}
}

// NewDeleteProjectIDBuildBuildIDOK creates a DeleteProjectIDBuildBuildIDOK with default headers values
func NewDeleteProjectIDBuildBuildIDOK() *DeleteProjectIDBuildBuildIDOK {
	return &DeleteProjectIDBuildBuildIDOK{}
}

/*
DeleteProjectIDBuildBuildIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteProjectIDBuildBuildIDOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelDeleteResponse
}

// IsSuccess returns true when this delete project Id build build Id o k response has a 2xx status code
func (o *DeleteProjectIDBuildBuildIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete project Id build build Id o k response has a 3xx status code
func (o *DeleteProjectIDBuildBuildIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id build build Id o k response has a 4xx status code
func (o *DeleteProjectIDBuildBuildIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete project Id build build Id o k response has a 5xx status code
func (o *DeleteProjectIDBuildBuildIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project Id build build Id o k response a status code equal to that given
func (o *DeleteProjectIDBuildBuildIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete project Id build build Id o k response
func (o *DeleteProjectIDBuildBuildIDOK) Code() int {
	return 200
}

func (o *DeleteProjectIDBuildBuildIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdOK %s", 200, payload)
}

func (o *DeleteProjectIDBuildBuildIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdOK %s", 200, payload)
}

func (o *DeleteProjectIDBuildBuildIDOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelDeleteResponse {
	return o.Payload
}

func (o *DeleteProjectIDBuildBuildIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesBuildModelDeleteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteProjectIDBuildBuildIDBadRequest creates a DeleteProjectIDBuildBuildIDBadRequest with default headers values
func NewDeleteProjectIDBuildBuildIDBadRequest() *DeleteProjectIDBuildBuildIDBadRequest {
	return &DeleteProjectIDBuildBuildIDBadRequest{}
}

/*
DeleteProjectIDBuildBuildIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteProjectIDBuildBuildIDBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete project Id build build Id bad request response has a 2xx status code
func (o *DeleteProjectIDBuildBuildIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete project Id build build Id bad request response has a 3xx status code
func (o *DeleteProjectIDBuildBuildIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id build build Id bad request response has a 4xx status code
func (o *DeleteProjectIDBuildBuildIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete project Id build build Id bad request response has a 5xx status code
func (o *DeleteProjectIDBuildBuildIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project Id build build Id bad request response a status code equal to that given
func (o *DeleteProjectIDBuildBuildIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete project Id build build Id bad request response
func (o *DeleteProjectIDBuildBuildIDBadRequest) Code() int {
	return 400
}

func (o *DeleteProjectIDBuildBuildIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdBadRequest %s", 400, payload)
}

func (o *DeleteProjectIDBuildBuildIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdBadRequest %s", 400, payload)
}

func (o *DeleteProjectIDBuildBuildIDBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteProjectIDBuildBuildIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteProjectIDBuildBuildIDUnauthorized creates a DeleteProjectIDBuildBuildIDUnauthorized with default headers values
func NewDeleteProjectIDBuildBuildIDUnauthorized() *DeleteProjectIDBuildBuildIDUnauthorized {
	return &DeleteProjectIDBuildBuildIDUnauthorized{}
}

/*
DeleteProjectIDBuildBuildIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteProjectIDBuildBuildIDUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete project Id build build Id unauthorized response has a 2xx status code
func (o *DeleteProjectIDBuildBuildIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete project Id build build Id unauthorized response has a 3xx status code
func (o *DeleteProjectIDBuildBuildIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id build build Id unauthorized response has a 4xx status code
func (o *DeleteProjectIDBuildBuildIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete project Id build build Id unauthorized response has a 5xx status code
func (o *DeleteProjectIDBuildBuildIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project Id build build Id unauthorized response a status code equal to that given
func (o *DeleteProjectIDBuildBuildIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete project Id build build Id unauthorized response
func (o *DeleteProjectIDBuildBuildIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteProjectIDBuildBuildIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdUnauthorized %s", 401, payload)
}

func (o *DeleteProjectIDBuildBuildIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdUnauthorized %s", 401, payload)
}

func (o *DeleteProjectIDBuildBuildIDUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteProjectIDBuildBuildIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteProjectIDBuildBuildIDNotFound creates a DeleteProjectIDBuildBuildIDNotFound with default headers values
func NewDeleteProjectIDBuildBuildIDNotFound() *DeleteProjectIDBuildBuildIDNotFound {
	return &DeleteProjectIDBuildBuildIDNotFound{}
}

/*
DeleteProjectIDBuildBuildIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteProjectIDBuildBuildIDNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete project Id build build Id not found response has a 2xx status code
func (o *DeleteProjectIDBuildBuildIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete project Id build build Id not found response has a 3xx status code
func (o *DeleteProjectIDBuildBuildIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id build build Id not found response has a 4xx status code
func (o *DeleteProjectIDBuildBuildIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete project Id build build Id not found response has a 5xx status code
func (o *DeleteProjectIDBuildBuildIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete project Id build build Id not found response a status code equal to that given
func (o *DeleteProjectIDBuildBuildIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete project Id build build Id not found response
func (o *DeleteProjectIDBuildBuildIDNotFound) Code() int {
	return 404
}

func (o *DeleteProjectIDBuildBuildIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdNotFound %s", 404, payload)
}

func (o *DeleteProjectIDBuildBuildIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdNotFound %s", 404, payload)
}

func (o *DeleteProjectIDBuildBuildIDNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteProjectIDBuildBuildIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteProjectIDBuildBuildIDInternalServerError creates a DeleteProjectIDBuildBuildIDInternalServerError with default headers values
func NewDeleteProjectIDBuildBuildIDInternalServerError() *DeleteProjectIDBuildBuildIDInternalServerError {
	return &DeleteProjectIDBuildBuildIDInternalServerError{}
}

/*
DeleteProjectIDBuildBuildIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteProjectIDBuildBuildIDInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this delete project Id build build Id internal server error response has a 2xx status code
func (o *DeleteProjectIDBuildBuildIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete project Id build build Id internal server error response has a 3xx status code
func (o *DeleteProjectIDBuildBuildIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete project Id build build Id internal server error response has a 4xx status code
func (o *DeleteProjectIDBuildBuildIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete project Id build build Id internal server error response has a 5xx status code
func (o *DeleteProjectIDBuildBuildIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete project Id build build Id internal server error response a status code equal to that given
func (o *DeleteProjectIDBuildBuildIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete project Id build build Id internal server error response
func (o *DeleteProjectIDBuildBuildIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteProjectIDBuildBuildIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdInternalServerError %s", 500, payload)
}

func (o *DeleteProjectIDBuildBuildIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /project/{id}/build/{buildId}][%d] deleteProjectIdBuildBuildIdInternalServerError %s", 500, payload)
}

func (o *DeleteProjectIDBuildBuildIDInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *DeleteProjectIDBuildBuildIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
