// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewDeleteProjectIDCacheParams creates a new DeleteProjectIDCacheParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectIDCacheParams() *DeleteProjectIDCacheParams {
	return NewDeleteProjectIDCacheParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteProjectIDCacheParamsWithTimeout creates a new DeleteProjectIDCacheParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectIDCacheParamsWithTimeout(timeout time.Duration) *DeleteProjectIDCacheParams {
	return &DeleteProjectIDCacheParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteProjectIDCacheParamsWithContext creates a new DeleteProjectIDCacheParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectIDCacheParams].
func NewDeleteProjectIDCacheParamsWithContext(ctx context.Context) *DeleteProjectIDCacheParams {
	return &DeleteProjectIDCacheParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteProjectIDCacheParamsWithHTTPClient creates a new DeleteProjectIDCacheParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectIDCacheParamsWithHTTPClient(client *http.Client) *DeleteProjectIDCacheParams {
	return &DeleteProjectIDCacheParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectIDCacheParams contains all the parameters to send to the API endpoint

	for the delete project ID cache operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectIDCacheParams struct {

	/* Branch.

	   Branch name
	*/
	Branch *string

	/* Fingerprint.

	   Cache fingerprint
	*/
	Fingerprint *string

	/* ID.

	   Project ID
	*/
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete project ID cache params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectIDCacheParams) WithDefaults() *DeleteProjectIDCacheParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project ID cache params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectIDCacheParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) WithTimeout(timeout time.Duration) *DeleteProjectIDCacheParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete project ID cache params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectIDCacheParams].
func (o *DeleteProjectIDCacheParams) WithContext(ctx context.Context) *DeleteProjectIDCacheParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project ID cache params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteProjectIDCacheParams].
func (o *DeleteProjectIDCacheParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) WithHTTPClient(client *http.Client) *DeleteProjectIDCacheParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) WithBranch(branch *string) *DeleteProjectIDCacheParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) SetBranch(branch *string) {
	o.Branch = branch
}

// WithFingerprint adds the fingerprint to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) WithFingerprint(fingerprint *string) *DeleteProjectIDCacheParams {
	o.SetFingerprint(fingerprint)
	return o
}

// SetFingerprint adds the fingerprint to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) SetFingerprint(fingerprint *string) {
	o.Fingerprint = fingerprint
}

// WithID adds the id to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) WithID(id int64) *DeleteProjectIDCacheParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete project ID cache params.
func (o *DeleteProjectIDCacheParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteProjectIDCacheParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Branch != nil {

		// query param branch
		var qrBranch string

		if o.Branch != nil {
			qrBranch = *o.Branch
		}
		qBranch := qrBranch
		if qBranch != "" {

			if err := r.SetQueryParam("branch", qBranch); err != nil {
				return err
			}
		}
	}

	if o.Fingerprint != nil {

		// query param fingerprint
		var qrFingerprint string

		if o.Fingerprint != nil {
			qrFingerprint = *o.Fingerprint
		}
		qFingerprint := qrFingerprint
		if qFingerprint != "" {

			if err := r.SetQueryParam("fingerprint", qFingerprint); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
