// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetProjectIDBuildsReader is a Reader for the GetProjectIDBuilds structure.
type GetProjectIDBuildsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectIDBuildsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectIDBuildsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProjectIDBuildsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProjectIDBuildsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProjectIDBuildsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /project/{id}/builds] GetProjectIDBuilds", response, response.Code())
	}
}

// NewGetProjectIDBuildsOK creates a GetProjectIDBuildsOK with default headers values
func NewGetProjectIDBuildsOK() *GetProjectIDBuildsOK {
	return &GetProjectIDBuildsOK{}
}

/*
GetProjectIDBuildsOK describes a response with status code 200, with default header values.

OK
*/
type GetProjectIDBuildsOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse
}

// IsSuccess returns true when this get project Id builds o k response has a 2xx status code
func (o *GetProjectIDBuildsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project Id builds o k response has a 3xx status code
func (o *GetProjectIDBuildsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id builds o k response has a 4xx status code
func (o *GetProjectIDBuildsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project Id builds o k response has a 5xx status code
func (o *GetProjectIDBuildsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id builds o k response a status code equal to that given
func (o *GetProjectIDBuildsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project Id builds o k response
func (o *GetProjectIDBuildsOK) Code() int {
	return 200
}

func (o *GetProjectIDBuildsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/builds][%d] getProjectIdBuildsOK %s", 200, payload)
}

func (o *GetProjectIDBuildsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/builds][%d] getProjectIdBuildsOK %s", 200, payload)
}

func (o *GetProjectIDBuildsOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse {
	return o.Payload
}

func (o *GetProjectIDBuildsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDBuildsBadRequest creates a GetProjectIDBuildsBadRequest with default headers values
func NewGetProjectIDBuildsBadRequest() *GetProjectIDBuildsBadRequest {
	return &GetProjectIDBuildsBadRequest{}
}

/*
GetProjectIDBuildsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProjectIDBuildsBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id builds bad request response has a 2xx status code
func (o *GetProjectIDBuildsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id builds bad request response has a 3xx status code
func (o *GetProjectIDBuildsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id builds bad request response has a 4xx status code
func (o *GetProjectIDBuildsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project Id builds bad request response has a 5xx status code
func (o *GetProjectIDBuildsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id builds bad request response a status code equal to that given
func (o *GetProjectIDBuildsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get project Id builds bad request response
func (o *GetProjectIDBuildsBadRequest) Code() int {
	return 400
}

func (o *GetProjectIDBuildsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/builds][%d] getProjectIdBuildsBadRequest %s", 400, payload)
}

func (o *GetProjectIDBuildsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/builds][%d] getProjectIdBuildsBadRequest %s", 400, payload)
}

func (o *GetProjectIDBuildsBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDBuildsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDBuildsUnauthorized creates a GetProjectIDBuildsUnauthorized with default headers values
func NewGetProjectIDBuildsUnauthorized() *GetProjectIDBuildsUnauthorized {
	return &GetProjectIDBuildsUnauthorized{}
}

/*
GetProjectIDBuildsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProjectIDBuildsUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id builds unauthorized response has a 2xx status code
func (o *GetProjectIDBuildsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id builds unauthorized response has a 3xx status code
func (o *GetProjectIDBuildsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id builds unauthorized response has a 4xx status code
func (o *GetProjectIDBuildsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project Id builds unauthorized response has a 5xx status code
func (o *GetProjectIDBuildsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id builds unauthorized response a status code equal to that given
func (o *GetProjectIDBuildsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get project Id builds unauthorized response
func (o *GetProjectIDBuildsUnauthorized) Code() int {
	return 401
}

func (o *GetProjectIDBuildsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/builds][%d] getProjectIdBuildsUnauthorized %s", 401, payload)
}

func (o *GetProjectIDBuildsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/builds][%d] getProjectIdBuildsUnauthorized %s", 401, payload)
}

func (o *GetProjectIDBuildsUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDBuildsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDBuildsInternalServerError creates a GetProjectIDBuildsInternalServerError with default headers values
func NewGetProjectIDBuildsInternalServerError() *GetProjectIDBuildsInternalServerError {
	return &GetProjectIDBuildsInternalServerError{}
}

/*
GetProjectIDBuildsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProjectIDBuildsInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id builds internal server error response has a 2xx status code
func (o *GetProjectIDBuildsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id builds internal server error response has a 3xx status code
func (o *GetProjectIDBuildsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id builds internal server error response has a 4xx status code
func (o *GetProjectIDBuildsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project Id builds internal server error response has a 5xx status code
func (o *GetProjectIDBuildsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get project Id builds internal server error response a status code equal to that given
func (o *GetProjectIDBuildsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get project Id builds internal server error response
func (o *GetProjectIDBuildsInternalServerError) Code() int {
	return 500
}

func (o *GetProjectIDBuildsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/builds][%d] getProjectIdBuildsInternalServerError %s", 500, payload)
}

func (o *GetProjectIDBuildsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/builds][%d] getProjectIdBuildsInternalServerError %s", 500, payload)
}

func (o *GetProjectIDBuildsInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDBuildsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
