// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetProjectIDCacheMetricsParams creates a new GetProjectIDCacheMetricsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectIDCacheMetricsParams() *GetProjectIDCacheMetricsParams {
	return NewGetProjectIDCacheMetricsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetProjectIDCacheMetricsParamsWithTimeout creates a new GetProjectIDCacheMetricsParams object
// with the ability to set a timeout on a request.
func NewGetProjectIDCacheMetricsParamsWithTimeout(timeout time.Duration) *GetProjectIDCacheMetricsParams {
	return &GetProjectIDCacheMetricsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetProjectIDCacheMetricsParamsWithContext creates a new GetProjectIDCacheMetricsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDCacheMetricsParams].
func NewGetProjectIDCacheMetricsParamsWithContext(ctx context.Context) *GetProjectIDCacheMetricsParams {
	return &GetProjectIDCacheMetricsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetProjectIDCacheMetricsParamsWithHTTPClient creates a new GetProjectIDCacheMetricsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectIDCacheMetricsParamsWithHTTPClient(client *http.Client) *GetProjectIDCacheMetricsParams {
	return &GetProjectIDCacheMetricsParams{
		HTTPClient: client,
	}
}

/*
GetProjectIDCacheMetricsParams contains all the parameters to send to the API endpoint

	for the get project ID cache metrics operation.

	Typically these are written to a http.Request.
*/
type GetProjectIDCacheMetricsParams struct {

	/* Branch.

	   Branch name
	*/
	Branch *string

	/* Fingerprint.

	   Cache fingerprint
	*/
	Fingerprint *string

	/* ID.

	   Project ID
	*/
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get project ID cache metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDCacheMetricsParams) WithDefaults() *GetProjectIDCacheMetricsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project ID cache metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDCacheMetricsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) WithTimeout(timeout time.Duration) *GetProjectIDCacheMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get project ID cache metrics params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDCacheMetricsParams].
func (o *GetProjectIDCacheMetricsParams) WithContext(ctx context.Context) *GetProjectIDCacheMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project ID cache metrics params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDCacheMetricsParams].
func (o *GetProjectIDCacheMetricsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) WithHTTPClient(client *http.Client) *GetProjectIDCacheMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) WithBranch(branch *string) *GetProjectIDCacheMetricsParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) SetBranch(branch *string) {
	o.Branch = branch
}

// WithFingerprint adds the fingerprint to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) WithFingerprint(fingerprint *string) *GetProjectIDCacheMetricsParams {
	o.SetFingerprint(fingerprint)
	return o
}

// SetFingerprint adds the fingerprint to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) SetFingerprint(fingerprint *string) {
	o.Fingerprint = fingerprint
}

// WithID adds the id to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) WithID(id int64) *GetProjectIDCacheMetricsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project ID cache metrics params.
func (o *GetProjectIDCacheMetricsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetProjectIDCacheMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Branch != nil {

		// query param branch
		var qrBranch string

		if o.Branch != nil {
			qrBranch = *o.Branch
		}
		qBranch := qrBranch
		if qBranch != "" {

			if err := r.SetQueryParam("branch", qBranch); err != nil {
				return err
			}
		}
	}

	if o.Fingerprint != nil {

		// query param fingerprint
		var qrFingerprint string

		if o.Fingerprint != nil {
			qrFingerprint = *o.Fingerprint
		}
		qFingerprint := qrFingerprint
		if qFingerprint != "" {

			if err := r.SetQueryParam("fingerprint", qFingerprint); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
