// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetProjectIDBuildBuildIDLogsParams creates a new GetProjectIDBuildBuildIDLogsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectIDBuildBuildIDLogsParams() *GetProjectIDBuildBuildIDLogsParams {
	return NewGetProjectIDBuildBuildIDLogsParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetProjectIDBuildBuildIDLogsParamsWithTimeout creates a new GetProjectIDBuildBuildIDLogsParams object
// with the ability to set a timeout on a request.
func NewGetProjectIDBuildBuildIDLogsParamsWithTimeout(timeout time.Duration) *GetProjectIDBuildBuildIDLogsParams {
	return &GetProjectIDBuildBuildIDLogsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetProjectIDBuildBuildIDLogsParamsWithContext creates a new GetProjectIDBuildBuildIDLogsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDBuildBuildIDLogsParams].
func NewGetProjectIDBuildBuildIDLogsParamsWithContext(ctx context.Context) *GetProjectIDBuildBuildIDLogsParams {
	return &GetProjectIDBuildBuildIDLogsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetProjectIDBuildBuildIDLogsParamsWithHTTPClient creates a new GetProjectIDBuildBuildIDLogsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectIDBuildBuildIDLogsParamsWithHTTPClient(client *http.Client) *GetProjectIDBuildBuildIDLogsParams {
	return &GetProjectIDBuildBuildIDLogsParams{
		HTTPClient: client,
	}
}

/*
GetProjectIDBuildBuildIDLogsParams contains all the parameters to send to the API endpoint

	for the get project ID build build ID logs operation.

	Typically these are written to a http.Request.
*/
type GetProjectIDBuildBuildIDLogsParams struct {

	/* BuildID.

	   Build ID
	*/
	BuildID int64

	/* ID.

	   Project ID
	*/
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get project ID build build ID logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDBuildBuildIDLogsParams) WithDefaults() *GetProjectIDBuildBuildIDLogsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project ID build build ID logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDBuildBuildIDLogsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project ID build build ID logs params.
func (o *GetProjectIDBuildBuildIDLogsParams) WithTimeout(timeout time.Duration) *GetProjectIDBuildBuildIDLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project ID build build ID logs params.
func (o *GetProjectIDBuildBuildIDLogsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get project ID build build ID logs params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDBuildBuildIDLogsParams].
func (o *GetProjectIDBuildBuildIDLogsParams) WithContext(ctx context.Context) *GetProjectIDBuildBuildIDLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project ID build build ID logs params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDBuildBuildIDLogsParams].
func (o *GetProjectIDBuildBuildIDLogsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get project ID build build ID logs params.
func (o *GetProjectIDBuildBuildIDLogsParams) WithHTTPClient(client *http.Client) *GetProjectIDBuildBuildIDLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project ID build build ID logs params.
func (o *GetProjectIDBuildBuildIDLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildID adds the buildID to the get project ID build build ID logs params.
func (o *GetProjectIDBuildBuildIDLogsParams) WithBuildID(buildID int64) *GetProjectIDBuildBuildIDLogsParams {
	o.SetBuildID(buildID)
	return o
}

// SetBuildID adds the buildId to the get project ID build build ID logs params.
func (o *GetProjectIDBuildBuildIDLogsParams) SetBuildID(buildID int64) {
	o.BuildID = buildID
}

// WithID adds the id to the get project ID build build ID logs params.
func (o *GetProjectIDBuildBuildIDLogsParams) WithID(id int64) *GetProjectIDBuildBuildIDLogsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project ID build build ID logs params.
func (o *GetProjectIDBuildBuildIDLogsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetProjectIDBuildBuildIDLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param buildId
	if err := r.SetPathParam("buildId", conv.FormatInteger(o.BuildID)); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
