// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetProjectIDCacheMetricsReader is a Reader for the GetProjectIDCacheMetrics structure.
type GetProjectIDCacheMetricsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectIDCacheMetricsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectIDCacheMetricsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProjectIDCacheMetricsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProjectIDCacheMetricsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProjectIDCacheMetricsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProjectIDCacheMetricsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /project/{id}/cache/metrics] GetProjectIDCacheMetrics", response, response.Code())
	}
}

// NewGetProjectIDCacheMetricsOK creates a GetProjectIDCacheMetricsOK with default headers values
func NewGetProjectIDCacheMetricsOK() *GetProjectIDCacheMetricsOK {
	return &GetProjectIDCacheMetricsOK{}
}

/*
GetProjectIDCacheMetricsOK describes a response with status code 200, with default header values.

OK
*/
type GetProjectIDCacheMetricsOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse
}

// IsSuccess returns true when this get project Id cache metrics o k response has a 2xx status code
func (o *GetProjectIDCacheMetricsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project Id cache metrics o k response has a 3xx status code
func (o *GetProjectIDCacheMetricsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id cache metrics o k response has a 4xx status code
func (o *GetProjectIDCacheMetricsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project Id cache metrics o k response has a 5xx status code
func (o *GetProjectIDCacheMetricsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id cache metrics o k response a status code equal to that given
func (o *GetProjectIDCacheMetricsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project Id cache metrics o k response
func (o *GetProjectIDCacheMetricsOK) Code() int {
	return 200
}

func (o *GetProjectIDCacheMetricsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsOK %s", 200, payload)
}

func (o *GetProjectIDCacheMetricsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsOK %s", 200, payload)
}

func (o *GetProjectIDCacheMetricsOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse {
	return o.Payload
}

func (o *GetProjectIDCacheMetricsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDCacheMetricsBadRequest creates a GetProjectIDCacheMetricsBadRequest with default headers values
func NewGetProjectIDCacheMetricsBadRequest() *GetProjectIDCacheMetricsBadRequest {
	return &GetProjectIDCacheMetricsBadRequest{}
}

/*
GetProjectIDCacheMetricsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProjectIDCacheMetricsBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id cache metrics bad request response has a 2xx status code
func (o *GetProjectIDCacheMetricsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id cache metrics bad request response has a 3xx status code
func (o *GetProjectIDCacheMetricsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id cache metrics bad request response has a 4xx status code
func (o *GetProjectIDCacheMetricsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project Id cache metrics bad request response has a 5xx status code
func (o *GetProjectIDCacheMetricsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id cache metrics bad request response a status code equal to that given
func (o *GetProjectIDCacheMetricsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get project Id cache metrics bad request response
func (o *GetProjectIDCacheMetricsBadRequest) Code() int {
	return 400
}

func (o *GetProjectIDCacheMetricsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsBadRequest %s", 400, payload)
}

func (o *GetProjectIDCacheMetricsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsBadRequest %s", 400, payload)
}

func (o *GetProjectIDCacheMetricsBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDCacheMetricsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDCacheMetricsUnauthorized creates a GetProjectIDCacheMetricsUnauthorized with default headers values
func NewGetProjectIDCacheMetricsUnauthorized() *GetProjectIDCacheMetricsUnauthorized {
	return &GetProjectIDCacheMetricsUnauthorized{}
}

/*
GetProjectIDCacheMetricsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProjectIDCacheMetricsUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id cache metrics unauthorized response has a 2xx status code
func (o *GetProjectIDCacheMetricsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id cache metrics unauthorized response has a 3xx status code
func (o *GetProjectIDCacheMetricsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id cache metrics unauthorized response has a 4xx status code
func (o *GetProjectIDCacheMetricsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project Id cache metrics unauthorized response has a 5xx status code
func (o *GetProjectIDCacheMetricsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id cache metrics unauthorized response a status code equal to that given
func (o *GetProjectIDCacheMetricsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get project Id cache metrics unauthorized response
func (o *GetProjectIDCacheMetricsUnauthorized) Code() int {
	return 401
}

func (o *GetProjectIDCacheMetricsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsUnauthorized %s", 401, payload)
}

func (o *GetProjectIDCacheMetricsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsUnauthorized %s", 401, payload)
}

func (o *GetProjectIDCacheMetricsUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDCacheMetricsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDCacheMetricsNotFound creates a GetProjectIDCacheMetricsNotFound with default headers values
func NewGetProjectIDCacheMetricsNotFound() *GetProjectIDCacheMetricsNotFound {
	return &GetProjectIDCacheMetricsNotFound{}
}

/*
GetProjectIDCacheMetricsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProjectIDCacheMetricsNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id cache metrics not found response has a 2xx status code
func (o *GetProjectIDCacheMetricsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id cache metrics not found response has a 3xx status code
func (o *GetProjectIDCacheMetricsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id cache metrics not found response has a 4xx status code
func (o *GetProjectIDCacheMetricsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get project Id cache metrics not found response has a 5xx status code
func (o *GetProjectIDCacheMetricsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get project Id cache metrics not found response a status code equal to that given
func (o *GetProjectIDCacheMetricsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get project Id cache metrics not found response
func (o *GetProjectIDCacheMetricsNotFound) Code() int {
	return 404
}

func (o *GetProjectIDCacheMetricsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsNotFound %s", 404, payload)
}

func (o *GetProjectIDCacheMetricsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsNotFound %s", 404, payload)
}

func (o *GetProjectIDCacheMetricsNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDCacheMetricsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetProjectIDCacheMetricsInternalServerError creates a GetProjectIDCacheMetricsInternalServerError with default headers values
func NewGetProjectIDCacheMetricsInternalServerError() *GetProjectIDCacheMetricsInternalServerError {
	return &GetProjectIDCacheMetricsInternalServerError{}
}

/*
GetProjectIDCacheMetricsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProjectIDCacheMetricsInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this get project Id cache metrics internal server error response has a 2xx status code
func (o *GetProjectIDCacheMetricsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get project Id cache metrics internal server error response has a 3xx status code
func (o *GetProjectIDCacheMetricsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project Id cache metrics internal server error response has a 4xx status code
func (o *GetProjectIDCacheMetricsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project Id cache metrics internal server error response has a 5xx status code
func (o *GetProjectIDCacheMetricsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get project Id cache metrics internal server error response a status code equal to that given
func (o *GetProjectIDCacheMetricsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get project Id cache metrics internal server error response
func (o *GetProjectIDCacheMetricsInternalServerError) Code() int {
	return 500
}

func (o *GetProjectIDCacheMetricsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsInternalServerError %s", 500, payload)
}

func (o *GetProjectIDCacheMetricsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{id}/cache/metrics][%d] getProjectIdCacheMetricsInternalServerError %s", 500, payload)
}

func (o *GetProjectIDCacheMetricsInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetProjectIDCacheMetricsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
