// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetProjectIDCacheEntriesParams creates a new GetProjectIDCacheEntriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectIDCacheEntriesParams() *GetProjectIDCacheEntriesParams {
	return NewGetProjectIDCacheEntriesParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetProjectIDCacheEntriesParamsWithTimeout creates a new GetProjectIDCacheEntriesParams object
// with the ability to set a timeout on a request.
func NewGetProjectIDCacheEntriesParamsWithTimeout(timeout time.Duration) *GetProjectIDCacheEntriesParams {
	return &GetProjectIDCacheEntriesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetProjectIDCacheEntriesParamsWithContext creates a new GetProjectIDCacheEntriesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDCacheEntriesParams].
func NewGetProjectIDCacheEntriesParamsWithContext(ctx context.Context) *GetProjectIDCacheEntriesParams {
	return &GetProjectIDCacheEntriesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetProjectIDCacheEntriesParamsWithHTTPClient creates a new GetProjectIDCacheEntriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectIDCacheEntriesParamsWithHTTPClient(client *http.Client) *GetProjectIDCacheEntriesParams {
	return &GetProjectIDCacheEntriesParams{
		HTTPClient: client,
	}
}

/*
GetProjectIDCacheEntriesParams contains all the parameters to send to the API endpoint

	for the get project ID cache entries operation.

	Typically these are written to a http.Request.
*/
type GetProjectIDCacheEntriesParams struct {

	/* Branch.

	   Branch name
	*/
	Branch string

	/* ID.

	   Project ID
	*/
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get project ID cache entries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDCacheEntriesParams) WithDefaults() *GetProjectIDCacheEntriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project ID cache entries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDCacheEntriesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project ID cache entries params.
func (o *GetProjectIDCacheEntriesParams) WithTimeout(timeout time.Duration) *GetProjectIDCacheEntriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project ID cache entries params.
func (o *GetProjectIDCacheEntriesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get project ID cache entries params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDCacheEntriesParams].
func (o *GetProjectIDCacheEntriesParams) WithContext(ctx context.Context) *GetProjectIDCacheEntriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project ID cache entries params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDCacheEntriesParams].
func (o *GetProjectIDCacheEntriesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get project ID cache entries params.
func (o *GetProjectIDCacheEntriesParams) WithHTTPClient(client *http.Client) *GetProjectIDCacheEntriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project ID cache entries params.
func (o *GetProjectIDCacheEntriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the get project ID cache entries params.
func (o *GetProjectIDCacheEntriesParams) WithBranch(branch string) *GetProjectIDCacheEntriesParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the get project ID cache entries params.
func (o *GetProjectIDCacheEntriesParams) SetBranch(branch string) {
	o.Branch = branch
}

// WithID adds the id to the get project ID cache entries params.
func (o *GetProjectIDCacheEntriesParams) WithID(id int64) *GetProjectIDCacheEntriesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project ID cache entries params.
func (o *GetProjectIDCacheEntriesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetProjectIDCacheEntriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// query param branch
	qrBranch := o.Branch
	qBranch := qrBranch
	if qBranch != "" {

		if err := r.SetQueryParam("branch", qBranch); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
