// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetProjectIDBuildBuildIDDownloadParams creates a new GetProjectIDBuildBuildIDDownloadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectIDBuildBuildIDDownloadParams() *GetProjectIDBuildBuildIDDownloadParams {
	return NewGetProjectIDBuildBuildIDDownloadParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetProjectIDBuildBuildIDDownloadParamsWithTimeout creates a new GetProjectIDBuildBuildIDDownloadParams object
// with the ability to set a timeout on a request.
func NewGetProjectIDBuildBuildIDDownloadParamsWithTimeout(timeout time.Duration) *GetProjectIDBuildBuildIDDownloadParams {
	return &GetProjectIDBuildBuildIDDownloadParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetProjectIDBuildBuildIDDownloadParamsWithContext creates a new GetProjectIDBuildBuildIDDownloadParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDBuildBuildIDDownloadParams].
func NewGetProjectIDBuildBuildIDDownloadParamsWithContext(ctx context.Context) *GetProjectIDBuildBuildIDDownloadParams {
	return &GetProjectIDBuildBuildIDDownloadParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetProjectIDBuildBuildIDDownloadParamsWithHTTPClient creates a new GetProjectIDBuildBuildIDDownloadParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectIDBuildBuildIDDownloadParamsWithHTTPClient(client *http.Client) *GetProjectIDBuildBuildIDDownloadParams {
	return &GetProjectIDBuildBuildIDDownloadParams{
		HTTPClient: client,
	}
}

/*
GetProjectIDBuildBuildIDDownloadParams contains all the parameters to send to the API endpoint

	for the get project ID build build ID download operation.

	Typically these are written to a http.Request.
*/
type GetProjectIDBuildBuildIDDownloadParams struct {

	/* BuildID.

	   Build ID
	*/
	BuildID int64

	/* ID.

	   Project ID
	*/
	ID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get project ID build build ID download params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDBuildBuildIDDownloadParams) WithDefaults() *GetProjectIDBuildBuildIDDownloadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project ID build build ID download params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectIDBuildBuildIDDownloadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project ID build build ID download params.
func (o *GetProjectIDBuildBuildIDDownloadParams) WithTimeout(timeout time.Duration) *GetProjectIDBuildBuildIDDownloadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project ID build build ID download params.
func (o *GetProjectIDBuildBuildIDDownloadParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get project ID build build ID download params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDBuildBuildIDDownloadParams].
func (o *GetProjectIDBuildBuildIDDownloadParams) WithContext(ctx context.Context) *GetProjectIDBuildBuildIDDownloadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project ID build build ID download params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectIDBuildBuildIDDownloadParams].
func (o *GetProjectIDBuildBuildIDDownloadParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get project ID build build ID download params.
func (o *GetProjectIDBuildBuildIDDownloadParams) WithHTTPClient(client *http.Client) *GetProjectIDBuildBuildIDDownloadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project ID build build ID download params.
func (o *GetProjectIDBuildBuildIDDownloadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildID adds the buildID to the get project ID build build ID download params.
func (o *GetProjectIDBuildBuildIDDownloadParams) WithBuildID(buildID int64) *GetProjectIDBuildBuildIDDownloadParams {
	o.SetBuildID(buildID)
	return o
}

// SetBuildID adds the buildId to the get project ID build build ID download params.
func (o *GetProjectIDBuildBuildIDDownloadParams) SetBuildID(buildID int64) {
	o.BuildID = buildID
}

// WithID adds the id to the get project ID build build ID download params.
func (o *GetProjectIDBuildBuildIDDownloadParams) WithID(id int64) *GetProjectIDBuildBuildIDDownloadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project ID build build ID download params.
func (o *GetProjectIDBuildBuildIDDownloadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetProjectIDBuildBuildIDDownloadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param buildId
	if err := r.SetPathParam("buildId", conv.FormatInteger(o.BuildID)); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", conv.FormatInteger(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
