// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostProjectIDBuildReader is a Reader for the PostProjectIDBuild structure.
type PostProjectIDBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectIDBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostProjectIDBuildOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostProjectIDBuildBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostProjectIDBuildUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostProjectIDBuildNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostProjectIDBuildInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /project/{id}/build] PostProjectIDBuild", response, response.Code())
	}
}

// NewPostProjectIDBuildOK creates a PostProjectIDBuildOK with default headers values
func NewPostProjectIDBuildOK() *PostProjectIDBuildOK {
	return &PostProjectIDBuildOK{}
}

/*
PostProjectIDBuildOK describes a response with status code 200, with default header values.

OK
*/
type PostProjectIDBuildOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse
}

// IsSuccess returns true when this post project Id build o k response has a 2xx status code
func (o *PostProjectIDBuildOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post project Id build o k response has a 3xx status code
func (o *PostProjectIDBuildOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project Id build o k response has a 4xx status code
func (o *PostProjectIDBuildOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post project Id build o k response has a 5xx status code
func (o *PostProjectIDBuildOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post project Id build o k response a status code equal to that given
func (o *PostProjectIDBuildOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post project Id build o k response
func (o *PostProjectIDBuildOK) Code() int {
	return 200
}

func (o *PostProjectIDBuildOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildOK %s", 200, payload)
}

func (o *PostProjectIDBuildOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildOK %s", 200, payload)
}

func (o *PostProjectIDBuildOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse {
	return o.Payload
}

func (o *PostProjectIDBuildOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostProjectIDBuildBadRequest creates a PostProjectIDBuildBadRequest with default headers values
func NewPostProjectIDBuildBadRequest() *PostProjectIDBuildBadRequest {
	return &PostProjectIDBuildBadRequest{}
}

/*
PostProjectIDBuildBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostProjectIDBuildBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this post project Id build bad request response has a 2xx status code
func (o *PostProjectIDBuildBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post project Id build bad request response has a 3xx status code
func (o *PostProjectIDBuildBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project Id build bad request response has a 4xx status code
func (o *PostProjectIDBuildBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post project Id build bad request response has a 5xx status code
func (o *PostProjectIDBuildBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post project Id build bad request response a status code equal to that given
func (o *PostProjectIDBuildBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post project Id build bad request response
func (o *PostProjectIDBuildBadRequest) Code() int {
	return 400
}

func (o *PostProjectIDBuildBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildBadRequest %s", 400, payload)
}

func (o *PostProjectIDBuildBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildBadRequest %s", 400, payload)
}

func (o *PostProjectIDBuildBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostProjectIDBuildBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostProjectIDBuildUnauthorized creates a PostProjectIDBuildUnauthorized with default headers values
func NewPostProjectIDBuildUnauthorized() *PostProjectIDBuildUnauthorized {
	return &PostProjectIDBuildUnauthorized{}
}

/*
PostProjectIDBuildUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostProjectIDBuildUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this post project Id build unauthorized response has a 2xx status code
func (o *PostProjectIDBuildUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post project Id build unauthorized response has a 3xx status code
func (o *PostProjectIDBuildUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project Id build unauthorized response has a 4xx status code
func (o *PostProjectIDBuildUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post project Id build unauthorized response has a 5xx status code
func (o *PostProjectIDBuildUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post project Id build unauthorized response a status code equal to that given
func (o *PostProjectIDBuildUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post project Id build unauthorized response
func (o *PostProjectIDBuildUnauthorized) Code() int {
	return 401
}

func (o *PostProjectIDBuildUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildUnauthorized %s", 401, payload)
}

func (o *PostProjectIDBuildUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildUnauthorized %s", 401, payload)
}

func (o *PostProjectIDBuildUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostProjectIDBuildUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostProjectIDBuildNotFound creates a PostProjectIDBuildNotFound with default headers values
func NewPostProjectIDBuildNotFound() *PostProjectIDBuildNotFound {
	return &PostProjectIDBuildNotFound{}
}

/*
PostProjectIDBuildNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostProjectIDBuildNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this post project Id build not found response has a 2xx status code
func (o *PostProjectIDBuildNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post project Id build not found response has a 3xx status code
func (o *PostProjectIDBuildNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project Id build not found response has a 4xx status code
func (o *PostProjectIDBuildNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post project Id build not found response has a 5xx status code
func (o *PostProjectIDBuildNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post project Id build not found response a status code equal to that given
func (o *PostProjectIDBuildNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post project Id build not found response
func (o *PostProjectIDBuildNotFound) Code() int {
	return 404
}

func (o *PostProjectIDBuildNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildNotFound %s", 404, payload)
}

func (o *PostProjectIDBuildNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildNotFound %s", 404, payload)
}

func (o *PostProjectIDBuildNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostProjectIDBuildNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostProjectIDBuildInternalServerError creates a PostProjectIDBuildInternalServerError with default headers values
func NewPostProjectIDBuildInternalServerError() *PostProjectIDBuildInternalServerError {
	return &PostProjectIDBuildInternalServerError{}
}

/*
PostProjectIDBuildInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostProjectIDBuildInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this post project Id build internal server error response has a 2xx status code
func (o *PostProjectIDBuildInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post project Id build internal server error response has a 3xx status code
func (o *PostProjectIDBuildInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post project Id build internal server error response has a 4xx status code
func (o *PostProjectIDBuildInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post project Id build internal server error response has a 5xx status code
func (o *PostProjectIDBuildInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post project Id build internal server error response a status code equal to that given
func (o *PostProjectIDBuildInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post project Id build internal server error response
func (o *PostProjectIDBuildInternalServerError) Code() int {
	return 500
}

func (o *PostProjectIDBuildInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildInternalServerError %s", 500, payload)
}

func (o *PostProjectIDBuildInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /project/{id}/build][%d] postProjectIdBuildInternalServerError %s", 500, payload)
}

func (o *PostProjectIDBuildInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostProjectIDBuildInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
