// Code generated by go-swagger; DO NOT EDIT.

package builds

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutProjectIDBuildBuildIDCancelReader is a Reader for the PutProjectIDBuildBuildIDCancel structure.
type PutProjectIDBuildBuildIDCancelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutProjectIDBuildBuildIDCancelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutProjectIDBuildBuildIDCancelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutProjectIDBuildBuildIDCancelBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutProjectIDBuildBuildIDCancelUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutProjectIDBuildBuildIDCancelNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutProjectIDBuildBuildIDCancelInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /project/{id}/build/{buildId}/cancel] PutProjectIDBuildBuildIDCancel", response, response.Code())
	}
}

// NewPutProjectIDBuildBuildIDCancelOK creates a PutProjectIDBuildBuildIDCancelOK with default headers values
func NewPutProjectIDBuildBuildIDCancelOK() *PutProjectIDBuildBuildIDCancelOK {
	return &PutProjectIDBuildBuildIDCancelOK{}
}

/*
PutProjectIDBuildBuildIDCancelOK describes a response with status code 200, with default header values.

OK
*/
type PutProjectIDBuildBuildIDCancelOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse
}

// IsSuccess returns true when this put project Id build build Id cancel o k response has a 2xx status code
func (o *PutProjectIDBuildBuildIDCancelOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put project Id build build Id cancel o k response has a 3xx status code
func (o *PutProjectIDBuildBuildIDCancelOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id build build Id cancel o k response has a 4xx status code
func (o *PutProjectIDBuildBuildIDCancelOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put project Id build build Id cancel o k response has a 5xx status code
func (o *PutProjectIDBuildBuildIDCancelOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put project Id build build Id cancel o k response a status code equal to that given
func (o *PutProjectIDBuildBuildIDCancelOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put project Id build build Id cancel o k response
func (o *PutProjectIDBuildBuildIDCancelOK) Code() int {
	return 200
}

func (o *PutProjectIDBuildBuildIDCancelOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelOK %s", 200, payload)
}

func (o *PutProjectIDBuildBuildIDCancelOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelOK %s", 200, payload)
}

func (o *PutProjectIDBuildBuildIDCancelOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse {
	return o.Payload
}

func (o *PutProjectIDBuildBuildIDCancelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutProjectIDBuildBuildIDCancelBadRequest creates a PutProjectIDBuildBuildIDCancelBadRequest with default headers values
func NewPutProjectIDBuildBuildIDCancelBadRequest() *PutProjectIDBuildBuildIDCancelBadRequest {
	return &PutProjectIDBuildBuildIDCancelBadRequest{}
}

/*
PutProjectIDBuildBuildIDCancelBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutProjectIDBuildBuildIDCancelBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this put project Id build build Id cancel bad request response has a 2xx status code
func (o *PutProjectIDBuildBuildIDCancelBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project Id build build Id cancel bad request response has a 3xx status code
func (o *PutProjectIDBuildBuildIDCancelBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id build build Id cancel bad request response has a 4xx status code
func (o *PutProjectIDBuildBuildIDCancelBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put project Id build build Id cancel bad request response has a 5xx status code
func (o *PutProjectIDBuildBuildIDCancelBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put project Id build build Id cancel bad request response a status code equal to that given
func (o *PutProjectIDBuildBuildIDCancelBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put project Id build build Id cancel bad request response
func (o *PutProjectIDBuildBuildIDCancelBadRequest) Code() int {
	return 400
}

func (o *PutProjectIDBuildBuildIDCancelBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelBadRequest %s", 400, payload)
}

func (o *PutProjectIDBuildBuildIDCancelBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelBadRequest %s", 400, payload)
}

func (o *PutProjectIDBuildBuildIDCancelBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *PutProjectIDBuildBuildIDCancelBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutProjectIDBuildBuildIDCancelUnauthorized creates a PutProjectIDBuildBuildIDCancelUnauthorized with default headers values
func NewPutProjectIDBuildBuildIDCancelUnauthorized() *PutProjectIDBuildBuildIDCancelUnauthorized {
	return &PutProjectIDBuildBuildIDCancelUnauthorized{}
}

/*
PutProjectIDBuildBuildIDCancelUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PutProjectIDBuildBuildIDCancelUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this put project Id build build Id cancel unauthorized response has a 2xx status code
func (o *PutProjectIDBuildBuildIDCancelUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project Id build build Id cancel unauthorized response has a 3xx status code
func (o *PutProjectIDBuildBuildIDCancelUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id build build Id cancel unauthorized response has a 4xx status code
func (o *PutProjectIDBuildBuildIDCancelUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this put project Id build build Id cancel unauthorized response has a 5xx status code
func (o *PutProjectIDBuildBuildIDCancelUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this put project Id build build Id cancel unauthorized response a status code equal to that given
func (o *PutProjectIDBuildBuildIDCancelUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the put project Id build build Id cancel unauthorized response
func (o *PutProjectIDBuildBuildIDCancelUnauthorized) Code() int {
	return 401
}

func (o *PutProjectIDBuildBuildIDCancelUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelUnauthorized %s", 401, payload)
}

func (o *PutProjectIDBuildBuildIDCancelUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelUnauthorized %s", 401, payload)
}

func (o *PutProjectIDBuildBuildIDCancelUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *PutProjectIDBuildBuildIDCancelUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutProjectIDBuildBuildIDCancelNotFound creates a PutProjectIDBuildBuildIDCancelNotFound with default headers values
func NewPutProjectIDBuildBuildIDCancelNotFound() *PutProjectIDBuildBuildIDCancelNotFound {
	return &PutProjectIDBuildBuildIDCancelNotFound{}
}

/*
PutProjectIDBuildBuildIDCancelNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutProjectIDBuildBuildIDCancelNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this put project Id build build Id cancel not found response has a 2xx status code
func (o *PutProjectIDBuildBuildIDCancelNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project Id build build Id cancel not found response has a 3xx status code
func (o *PutProjectIDBuildBuildIDCancelNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id build build Id cancel not found response has a 4xx status code
func (o *PutProjectIDBuildBuildIDCancelNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put project Id build build Id cancel not found response has a 5xx status code
func (o *PutProjectIDBuildBuildIDCancelNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put project Id build build Id cancel not found response a status code equal to that given
func (o *PutProjectIDBuildBuildIDCancelNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put project Id build build Id cancel not found response
func (o *PutProjectIDBuildBuildIDCancelNotFound) Code() int {
	return 404
}

func (o *PutProjectIDBuildBuildIDCancelNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelNotFound %s", 404, payload)
}

func (o *PutProjectIDBuildBuildIDCancelNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelNotFound %s", 404, payload)
}

func (o *PutProjectIDBuildBuildIDCancelNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *PutProjectIDBuildBuildIDCancelNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutProjectIDBuildBuildIDCancelInternalServerError creates a PutProjectIDBuildBuildIDCancelInternalServerError with default headers values
func NewPutProjectIDBuildBuildIDCancelInternalServerError() *PutProjectIDBuildBuildIDCancelInternalServerError {
	return &PutProjectIDBuildBuildIDCancelInternalServerError{}
}

/*
PutProjectIDBuildBuildIDCancelInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutProjectIDBuildBuildIDCancelInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this put project Id build build Id cancel internal server error response has a 2xx status code
func (o *PutProjectIDBuildBuildIDCancelInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put project Id build build Id cancel internal server error response has a 3xx status code
func (o *PutProjectIDBuildBuildIDCancelInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put project Id build build Id cancel internal server error response has a 4xx status code
func (o *PutProjectIDBuildBuildIDCancelInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put project Id build build Id cancel internal server error response has a 5xx status code
func (o *PutProjectIDBuildBuildIDCancelInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put project Id build build Id cancel internal server error response a status code equal to that given
func (o *PutProjectIDBuildBuildIDCancelInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put project Id build build Id cancel internal server error response
func (o *PutProjectIDBuildBuildIDCancelInternalServerError) Code() int {
	return 500
}

func (o *PutProjectIDBuildBuildIDCancelInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelInternalServerError %s", 500, payload)
}

func (o *PutProjectIDBuildBuildIDCancelInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /project/{id}/build/{buildId}/cancel][%d] putProjectIdBuildBuildIdCancelInternalServerError %s", 500, payload)
}

func (o *PutProjectIDBuildBuildIDCancelInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *PutProjectIDBuildBuildIDCancelInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
