// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse github com flotio dev core api internal modules build model build response
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_build_model.BuildResponse
type GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse struct {

	// build
	Build *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildDTO `json:"build,omitempty"`
}

// Validate validates this github com flotio dev core api internal modules build model build response
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuild(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse) validateBuild(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Build) { // not required
		return nil
	}

	if m.Build != nil {
		if err := m.Build.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("build")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("build")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this github com flotio dev core api internal modules build model build response based on the context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBuild(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse) contextValidateBuild(ctx context.Context, formats strfmt.Registry) error {

	if m.Build != nil {

		if typeutils.IsZero(m.Build) { // not required
			return nil
		}

		if err := m.Build.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("build")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("build")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
