// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse github com flotio dev core api internal modules build model builds response
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_build_model.BuildsResponse
type GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse struct {

	// builds
	Builds []*GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildDTO `json:"builds"`
}

// Validate validates this github com flotio dev core api internal modules build model builds response
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuilds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse) validateBuilds(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Builds) { // not required
		return nil
	}

	for i := 0; i < len(m.Builds); i++ {
		if typeutils.IsZero(m.Builds[i]) { // not required
			continue
		}

		if m.Builds[i] != nil {
			if err := m.Builds[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("builds" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("builds" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this github com flotio dev core api internal modules build model builds response based on the context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBuilds(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse) contextValidateBuilds(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Builds); i++ {

		if m.Builds[i] != nil {

			if typeutils.IsZero(m.Builds[i]) { // not required
				return nil
			}

			if err := m.Builds[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("builds" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("builds" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesBuildModelBuildsResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
