// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedBranchPattern github com flotio dev core api internal common database watched branch pattern
//
// swagger:model github_com_flotio-dev_core-api_internal_common_database.WatchedBranchPattern
type GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedBranchPattern struct {

	// pattern
	Pattern string `json:"pattern,omitempty"`

	// "source" or "target"
	Target string `json:"target,omitempty"`

	// "include" or "exclude"
	Type string `json:"type,omitempty"`
}

// Validate validates this github com flotio dev core api internal common database watched branch pattern
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedBranchPattern) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal common database watched branch pattern based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedBranchPattern) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedBranchPattern) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedBranchPattern) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedBranchPattern
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
