// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalModulesUserModelRegisterRequest github com flotio dev core api internal modules user model register request
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_user_model.RegisterRequest
type GithubComFlotioDevCoreAPIInternalModulesUserModelRegisterRequest struct {

	// email
	Email string `json:"email,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this github com flotio dev core api internal modules user model register request
func (m *GithubComFlotioDevCoreAPIInternalModulesUserModelRegisterRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal modules user model register request based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesUserModelRegisterRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesUserModelRegisterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesUserModelRegisterRequest) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesUserModelRegisterRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
