// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalCommonDatabaseEnvVariable github com flotio dev core api internal common database env variable
//
// swagger:model github_com_flotio-dev_core-api_internal_common_database.EnvVariable
type GithubComFlotioDevCoreAPIInternalCommonDatabaseEnvVariable struct {

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this github com flotio dev core api internal common database env variable
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnvVariable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal common database env variable based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnvVariable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnvVariable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnvVariable) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalCommonDatabaseEnvVariable
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
