// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials github com flotio dev core api internal common database google play credentials
//
// swagger:model github_com_flotio-dev_core-api_internal_common_database.GooglePlayCredentials
type GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// Base64 encoded JSON
	Credentials string `json:"credentials,omitempty"`

	// deleted at
	DeletedAt *GormDeletedAt `json:"deletedAt,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// Friendly name
	Name string `json:"name,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`

	// user
	User *GithubComFlotioDevCoreAPIInternalCommonDatabaseUser `json:"user,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this github com flotio dev core api internal common database google play credentials
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials) validateDeletedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DeletedAt) { // not required
		return nil
	}

	if m.DeletedAt != nil {
		if err := m.DeletedAt.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials) validateUser(formats strfmt.Registry) error {
	if typeutils.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {
		if err := m.User.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("user")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("user")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this github com flotio dev core api internal common database google play credentials based on the context it is used
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeletedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUser(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials) contextValidateDeletedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.DeletedAt != nil {

		if typeutils.IsZero(m.DeletedAt) { // not required
			return nil
		}

		if err := m.DeletedAt.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials) contextValidateUser(ctx context.Context, formats strfmt.Registry) error {

	if m.User != nil {

		if typeutils.IsZero(m.User) { // not required
			return nil
		}

		if err := m.User.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("user")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("user")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalCommonDatabaseGooglePlayCredentials
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
