// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse github com flotio dev core api internal modules github model post installation response
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_github_model.PostInstallationResponse
type GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse struct {

	// installation id
	// Example: 12345678
	InstallationID int64 `json:"installation_id,omitempty"`
}

// Validate validates this github com flotio dev core api internal modules github model post installation response
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal modules github model post installation response based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesGithubModelPostInstallationResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
