// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization github com flotio dev core api internal common database organization
//
// swagger:model github_com_flotio-dev_core-api_internal_common_database.Organization
type GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// deleted at
	DeletedAt *GormDeletedAt `json:"deletedAt,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// github installation
	GithubInstallation *GithubComFlotioDevCoreAPIInternalCommonDatabaseGithubInstallation `json:"githubInstallation,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// Validate validates this github com flotio dev core api internal common database organization
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGithubInstallation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization) validateDeletedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DeletedAt) { // not required
		return nil
	}

	if m.DeletedAt != nil {
		if err := m.DeletedAt.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization) validateGithubInstallation(formats strfmt.Registry) error {
	if typeutils.IsZero(m.GithubInstallation) { // not required
		return nil
	}

	if m.GithubInstallation != nil {
		if err := m.GithubInstallation.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("githubInstallation")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("githubInstallation")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this github com flotio dev core api internal common database organization based on the context it is used
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeletedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGithubInstallation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization) contextValidateDeletedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.DeletedAt != nil {

		if typeutils.IsZero(m.DeletedAt) { // not required
			return nil
		}

		if err := m.DeletedAt.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization) contextValidateGithubInstallation(ctx context.Context, formats strfmt.Registry) error {

	if m.GithubInstallation != nil {

		if typeutils.IsZero(m.GithubInstallation) { // not required
			return nil
		}

		if err := m.GithubInstallation.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("githubInstallation")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("githubInstallation")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalCommonDatabaseOrganization
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
