// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedTagPattern github com flotio dev core api internal common database watched tag pattern
//
// swagger:model github_com_flotio-dev_core-api_internal_common_database.WatchedTagPattern
type GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedTagPattern struct {

	// pattern
	Pattern string `json:"pattern,omitempty"`

	// "include" or "exclude"
	Type string `json:"type,omitempty"`
}

// Validate validates this github com flotio dev core api internal common database watched tag pattern
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedTagPattern) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal common database watched tag pattern based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedTagPattern) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedTagPattern) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedTagPattern) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalCommonDatabaseWatchedTagPattern
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
