// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheEntryDTO github com flotio dev core api internal modules build model cache entry d t o
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_build_model.CacheEntryDTO
type GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheEntryDTO struct {

	// fingerprint
	Fingerprint string `json:"fingerprint,omitempty"`

	// last modified at
	LastModifiedAt string `json:"last_modified_at,omitempty"`

	// object count
	ObjectCount int64 `json:"object_count,omitempty"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// total size bytes
	TotalSizeBytes int64 `json:"total_size_bytes,omitempty"`
}

// Validate validates this github com flotio dev core api internal modules build model cache entry d t o
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheEntryDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal modules build model cache entry d t o based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheEntryDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheEntryDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheEntryDTO) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheEntryDTO
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
