// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalModulesBuildModelCachePurgeResponse github com flotio dev core api internal modules build model cache purge response
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_build_model.CachePurgeResponse
type GithubComFlotioDevCoreAPIInternalModulesBuildModelCachePurgeResponse struct {

	// deleted objects
	DeletedObjects int64 `json:"deleted_objects,omitempty"`

	// fingerprint
	Fingerprint string `json:"fingerprint,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this github com flotio dev core api internal modules build model cache purge response
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCachePurgeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal modules build model cache purge response based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCachePurgeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCachePurgeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCachePurgeResponse) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesBuildModelCachePurgeResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
