// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild github com flotio dev core api internal common database build
//
// swagger:model github_com_flotio-dev_core-api_internal_common_database.Build
type GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild struct {

	// S3 key for the build artifact (e.g., "builds/123/app-release.apk")
	ApkURL string `json:"apk_url,omitempty"`

	// build mode
	BuildMode string `json:"build_mode,omitempty"`

	// build target
	BuildTarget string `json:"build_target,omitempty"`

	// Kubernetes container ID
	ContainerID string `json:"container_id,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// deleted at
	DeletedAt *GormDeletedAt `json:"deletedAt,omitempty"`

	// build duration in seconds
	Duration int64 `json:"duration,omitempty"`

	// flutter channel
	FlutterChannel string `json:"flutter_channel,omitempty"`

	// git branch
	GitBranch string `json:"git_branch,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// logs
	Logs []*GithubComFlotioDevCoreAPIInternalCommonDatabaseLog `json:"logs"`

	// platform
	Platform string `json:"platform,omitempty"`

	// project
	Project *GithubComFlotioDevCoreAPIInternalCommonDatabaseProject `json:"project,omitempty"`

	// project id
	ProjectID int64 `json:"project_id,omitempty"`

	// waiting, pending, running, success, failed, cancelled
	Status string `json:"status,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// Validate validates this github com flotio dev core api internal common database build
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProject(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) validateDeletedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DeletedAt) { // not required
		return nil
	}

	if m.DeletedAt != nil {
		if err := m.DeletedAt.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) validateLogs(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Logs) { // not required
		return nil
	}

	for i := 0; i < len(m.Logs); i++ {
		if typeutils.IsZero(m.Logs[i]) { // not required
			continue
		}

		if m.Logs[i] != nil {
			if err := m.Logs[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("logs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("logs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) validateProject(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Project) { // not required
		return nil
	}

	if m.Project != nil {
		if err := m.Project.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("project")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("project")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this github com flotio dev core api internal common database build based on the context it is used
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeletedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLogs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProject(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) contextValidateDeletedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.DeletedAt != nil {

		if typeutils.IsZero(m.DeletedAt) { // not required
			return nil
		}

		if err := m.DeletedAt.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) contextValidateLogs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Logs); i++ {

		if m.Logs[i] != nil {

			if typeutils.IsZero(m.Logs[i]) { // not required
				return nil
			}

			if err := m.Logs[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("logs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("logs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) contextValidateProject(ctx context.Context, formats strfmt.Registry) error {

	if m.Project != nil {

		if typeutils.IsZero(m.Project) { // not required
			return nil
		}

		if err := m.Project.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("project")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("project")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalCommonDatabaseBuild
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
