// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse github com flotio dev core api internal modules build model cache metrics response
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_build_model.CacheMetricsResponse
type GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse struct {

	// fingerprint
	Fingerprint string `json:"fingerprint,omitempty"`

	// generated at
	GeneratedAt string `json:"generated_at,omitempty"`

	// last modified at
	LastModifiedAt string `json:"last_modified_at,omitempty"`

	// metrics requests
	MetricsRequests int64 `json:"metrics_requests,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// object count
	ObjectCount int64 `json:"object_count,omitempty"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// purge requests
	PurgeRequests int64 `json:"purge_requests,omitempty"`

	// purged objects
	PurgedObjects int64 `json:"purged_objects,omitempty"`

	// retention ttl hours
	RetentionTTLHours int64 `json:"retention_ttl_hours,omitempty"`

	// total size bytes
	TotalSizeBytes int64 `json:"total_size_bytes,omitempty"`
}

// Validate validates this github com flotio dev core api internal modules build model cache metrics response
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal modules build model cache metrics response based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesBuildModelCacheMetricsResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
