// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv github com flotio dev core api internal common database env
//
// swagger:model github_com_flotio-dev_core-api_internal_common_database.Env
type GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// deleted at
	DeletedAt *GormDeletedAt `json:"deletedAt,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// True if Value is base64 encoded (for binary files)
	IsBase64 bool `json:"is_base64,omitempty"`

	// Variable name or file identifier
	Key string `json:"key,omitempty"`

	// Target path for files (e.g., "android/app/google-services.json")
	Path string `json:"path,omitempty"`

	// project
	Project *GithubComFlotioDevCoreAPIInternalCommonDatabaseProject `json:"project,omitempty"`

	// Nullable: can be associated to a project
	ProjectID int64 `json:"project_id,omitempty"`

	// "env" for environment variable, "file" for file
	Type string `json:"type,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`

	// user
	User *GithubComFlotioDevCoreAPIInternalCommonDatabaseUser `json:"user,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`

	// Variable value or file content (base64 for binary)
	Value string `json:"value,omitempty"`
}

// Validate validates this github com flotio dev core api internal common database env
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProject(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) validateDeletedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DeletedAt) { // not required
		return nil
	}

	if m.DeletedAt != nil {
		if err := m.DeletedAt.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) validateProject(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Project) { // not required
		return nil
	}

	if m.Project != nil {
		if err := m.Project.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("project")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("project")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) validateUser(formats strfmt.Registry) error {
	if typeutils.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {
		if err := m.User.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("user")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("user")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this github com flotio dev core api internal common database env based on the context it is used
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeletedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProject(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUser(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) contextValidateDeletedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.DeletedAt != nil {

		if typeutils.IsZero(m.DeletedAt) { // not required
			return nil
		}

		if err := m.DeletedAt.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) contextValidateProject(ctx context.Context, formats strfmt.Registry) error {

	if m.Project != nil {

		if typeutils.IsZero(m.Project) { // not required
			return nil
		}

		if err := m.Project.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("project")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("project")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) contextValidateUser(ctx context.Context, formats strfmt.Registry) error {

	if m.User != nil {

		if typeutils.IsZero(m.User) { // not required
			return nil
		}

		if err := m.User.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("user")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("user")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalCommonDatabaseEnv
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
