// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse github com flotio dev core api internal modules github model github tree response
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_github_model.GithubTreeResponse
type GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse struct {

	// owner
	// Example: flotio-dev
	Owner string `json:"owner,omitempty"`

	// repo
	// Example: api
	Repo string `json:"repo,omitempty"`

	// tree
	Tree []*GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem `json:"tree"`
}

// Validate validates this github com flotio dev core api internal modules github model github tree response
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTree(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse) validateTree(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Tree) { // not required
		return nil
	}

	for i := 0; i < len(m.Tree); i++ {
		if typeutils.IsZero(m.Tree[i]) { // not required
			continue
		}

		if m.Tree[i] != nil {
			if err := m.Tree[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("tree" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("tree" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this github com flotio dev core api internal modules github model github tree response based on the context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTree(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse) contextValidateTree(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Tree); i++ {

		if m.Tree[i] != nil {

			if typeutils.IsZero(m.Tree[i]) { // not required
				return nil
			}

			if err := m.Tree[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("tree" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("tree" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubTreeResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
