// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GithubComFlotioDevCoreAPIInternalModulesBuildModelLogsResponse github com flotio dev core api internal modules build model logs response
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_build_model.LogsResponse
type GithubComFlotioDevCoreAPIInternalModulesBuildModelLogsResponse struct {

	// logs
	Logs []string `json:"logs"`
}

// Validate validates this github com flotio dev core api internal modules build model logs response
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelLogsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com flotio dev core api internal modules build model logs response based on context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelLogsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelLogsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesBuildModelLogsResponse) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesBuildModelLogsResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
