// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem github com flotio dev core api internal modules github model github repo tree item
//
// swagger:model github_com_flotio-dev_core-api_internal_modules_github_model.GithubRepoTreeItem
type GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem struct {

	// children
	Children []*GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem `json:"children"`

	// name
	// Example: cmd
	Name string `json:"name,omitempty"`

	// path
	// Example: cmd/service
	Path string `json:"path,omitempty"`

	// type
	// Example: dir
	Type string `json:"type,omitempty"`

	// url
	// Example: https://github.com/...
	URL string `json:"url,omitempty"`
}

// Validate validates this github com flotio dev core api internal modules github model github repo tree item
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChildren(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem) validateChildren(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Children) { // not required
		return nil
	}

	for i := 0; i < len(m.Children); i++ {
		if typeutils.IsZero(m.Children[i]) { // not required
			continue
		}

		if m.Children[i] != nil {
			if err := m.Children[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("children" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("children" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this github com flotio dev core api internal modules github model github repo tree item based on the context it is used
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChildren(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem) contextValidateChildren(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Children); i++ {

		if m.Children[i] != nil {

			if typeutils.IsZero(m.Children[i]) { // not required
				return nil
			}

			if err := m.Children[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("children" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("children" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem) UnmarshalBinary(b []byte) error {
	var res GithubComFlotioDevCoreAPIInternalModulesGithubModelGithubRepoTreeItem
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
