// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GormDeletedAt gorm deleted at
//
// swagger:model gorm.DeletedAt
type GormDeletedAt struct {

	// time
	Time string `json:"time,omitempty"`

	// Valid is true if Time is not NULL
	Valid bool `json:"valid,omitempty"`
}

// Validate validates this gorm deleted at
func (m *GormDeletedAt) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gorm deleted at based on context it is used
func (m *GormDeletedAt) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GormDeletedAt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GormDeletedAt) UnmarshalBinary(b []byte) error {
	var res GormDeletedAt
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
