// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// InternalInfraKubernetesBuildConfig internal infra kubernetes build config
//
// swagger:model internal_infra_kubernetes.BuildConfig
type InternalInfraKubernetesBuildConfig struct {

	// build ID
	BuildID int64 `json:"buildID,omitempty"`

	// release, debug, profile
	BuildMode string `json:"buildMode,omitempty"`

	// apk, aab, ios, web
	BuildTarget string `json:"buildTarget,omitempty"`

	// cache enabled
	CacheEnabled bool `json:"cacheEnabled,omitempty"`

	// cache namespace
	CacheNamespace string `json:"cacheNamespace,omitempty"`

	// cache TTL hours
	CacheTTLHours int64 `json:"cacheTTLHours,omitempty"`

	// cache upload on success
	CacheUploadOnSuccess bool `json:"cacheUploadOnSuccess,omitempty"`

	// stable, beta, dev
	FlutterChannel string `json:"flutterChannel,omitempty"`

	// git branch
	GitBranch string `json:"gitBranch,omitempty"`

	// git token
	GitToken string `json:"gitToken,omitempty"`

	// git username
	GitUsername string `json:"gitUsername,omitempty"`

	// platform
	Platform string `json:"platform,omitempty"`

	// project
	Project *GithubComFlotioDevCoreAPIInternalCommonDatabaseProject `json:"project,omitempty"`

	// project config
	ProjectConfig *GithubComFlotioDevCoreAPIInternalCommonDatabaseProjectConfig `json:"projectConfig,omitempty"`
}

// Validate validates this internal infra kubernetes build config
func (m *InternalInfraKubernetesBuildConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProject(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalInfraKubernetesBuildConfig) validateProject(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Project) { // not required
		return nil
	}

	if m.Project != nil {
		if err := m.Project.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("project")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("project")
			}

			return err
		}
	}

	return nil
}

func (m *InternalInfraKubernetesBuildConfig) validateProjectConfig(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ProjectConfig) { // not required
		return nil
	}

	if m.ProjectConfig != nil {
		if err := m.ProjectConfig.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("projectConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("projectConfig")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this internal infra kubernetes build config based on the context it is used
func (m *InternalInfraKubernetesBuildConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProject(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProjectConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalInfraKubernetesBuildConfig) contextValidateProject(ctx context.Context, formats strfmt.Registry) error {

	if m.Project != nil {

		if typeutils.IsZero(m.Project) { // not required
			return nil
		}

		if err := m.Project.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("project")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("project")
			}

			return err
		}
	}

	return nil
}

func (m *InternalInfraKubernetesBuildConfig) contextValidateProjectConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.ProjectConfig != nil {

		if typeutils.IsZero(m.ProjectConfig) { // not required
			return nil
		}

		if err := m.ProjectConfig.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("projectConfig")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("projectConfig")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InternalInfraKubernetesBuildConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalInfraKubernetesBuildConfig) UnmarshalBinary(b []byte) error {
	var res InternalInfraKubernetesBuildConfig
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
