// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// InternalModulesProjectHandlerProjectResponse internal modules project handler project response
//
// swagger:model internal_modules_project_handler.ProjectResponse
type InternalModulesProjectHandlerProjectResponse struct {

	// project
	Project *InternalModulesProjectHandlerProject `json:"project,omitempty"`
}

// Validate validates this internal modules project handler project response
func (m *InternalModulesProjectHandlerProjectResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProject(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalModulesProjectHandlerProjectResponse) validateProject(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Project) { // not required
		return nil
	}

	if m.Project != nil {
		if err := m.Project.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("project")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("project")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this internal modules project handler project response based on the context it is used
func (m *InternalModulesProjectHandlerProjectResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProject(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalModulesProjectHandlerProjectResponse) contextValidateProject(ctx context.Context, formats strfmt.Registry) error {

	if m.Project != nil {

		if typeutils.IsZero(m.Project) { // not required
			return nil
		}

		if err := m.Project.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("project")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("project")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InternalModulesProjectHandlerProjectResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalModulesProjectHandlerProjectResponse) UnmarshalBinary(b []byte) error {
	var res InternalModulesProjectHandlerProjectResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
