// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// InternalModulesProjectHandlerProjectCreateRequest internal modules project handler project create request
//
// swagger:model internal_modules_project_handler.ProjectCreateRequest
type InternalModulesProjectHandlerProjectCreateRequest struct {

	// config
	Config *GithubComFlotioDevCoreAPIInternalCommonDatabaseProjectConfig `json:"config,omitempty"`

	// name
	// Example: My Flutter App
	Name string `json:"name,omitempty"`
}

// Validate validates this internal modules project handler project create request
func (m *InternalModulesProjectHandlerProjectCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalModulesProjectHandlerProjectCreateRequest) validateConfig(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Config) { // not required
		return nil
	}

	if m.Config != nil {
		if err := m.Config.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("config")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("config")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this internal modules project handler project create request based on the context it is used
func (m *InternalModulesProjectHandlerProjectCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalModulesProjectHandlerProjectCreateRequest) contextValidateConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.Config != nil {

		if typeutils.IsZero(m.Config) { // not required
			return nil
		}

		if err := m.Config.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("config")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("config")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InternalModulesProjectHandlerProjectCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalModulesProjectHandlerProjectCreateRequest) UnmarshalBinary(b []byte) error {
	var res InternalModulesProjectHandlerProjectCreateRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
