// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// InternalModulesBuildHandlerBuildLogsSyncResponse internal modules build handler build logs sync response
//
// swagger:model internal_modules_build_handler.BuildLogsSyncResponse
type InternalModulesBuildHandlerBuildLogsSyncResponse struct {

	// Time since build started in seconds
	ElapsedTime int64 `json:"elapsed_time,omitempty"`

	// has more
	HasMore bool `json:"has_more,omitempty"`

	// last line
	LastLine int64 `json:"last_line,omitempty"`

	// logs
	Logs []string `json:"logs"`

	// pod status
	PodStatus string `json:"pod_status,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this internal modules build handler build logs sync response
func (m *InternalModulesBuildHandlerBuildLogsSyncResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal modules build handler build logs sync response based on context it is used
func (m *InternalModulesBuildHandlerBuildLogsSyncResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalModulesBuildHandlerBuildLogsSyncResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalModulesBuildHandlerBuildLogsSyncResponse) UnmarshalBinary(b []byte) error {
	var res InternalModulesBuildHandlerBuildLogsSyncResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
