// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthMeParams creates a new GetAuthMeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthMeParams() *GetAuthMeParams {
	return NewGetAuthMeParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetAuthMeParamsWithTimeout creates a new GetAuthMeParams object
// with the ability to set a timeout on a request.
func NewGetAuthMeParamsWithTimeout(timeout time.Duration) *GetAuthMeParams {
	return &GetAuthMeParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetAuthMeParamsWithContext creates a new GetAuthMeParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAuthMeParams].
func NewGetAuthMeParamsWithContext(ctx context.Context) *GetAuthMeParams {
	return &GetAuthMeParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetAuthMeParamsWithHTTPClient creates a new GetAuthMeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthMeParamsWithHTTPClient(client *http.Client) *GetAuthMeParams {
	return &GetAuthMeParams{
		HTTPClient: client,
	}
}

/*
GetAuthMeParams contains all the parameters to send to the API endpoint

	for the get auth me operation.

	Typically these are written to a http.Request.
*/
type GetAuthMeParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get auth me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthMeParams) WithDefaults() *GetAuthMeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthMeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth me params.
func (o *GetAuthMeParams) WithTimeout(timeout time.Duration) *GetAuthMeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth me params.
func (o *GetAuthMeParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get auth me params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAuthMeParams].
func (o *GetAuthMeParams) WithContext(ctx context.Context) *GetAuthMeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth me params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetAuthMeParams].
func (o *GetAuthMeParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth me params.
func (o *GetAuthMeParams) WithHTTPClient(client *http.Client) *GetAuthMeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth me params.
func (o *GetAuthMeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetAuthMeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
