// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAuthMeReader is a Reader for the GetAuthMe structure.
type GetAuthMeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthMeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuthMeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAuthMeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAuthMeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /auth/me] GetAuthMe", response, response.Code())
	}
}

// NewGetAuthMeOK creates a GetAuthMeOK with default headers values
func NewGetAuthMeOK() *GetAuthMeOK {
	return &GetAuthMeOK{}
}

/*
GetAuthMeOK describes a response with status code 200, with default header values.

OK
*/
type GetAuthMeOK struct {
	Payload any
}

// IsSuccess returns true when this get auth me o k response has a 2xx status code
func (o *GetAuthMeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get auth me o k response has a 3xx status code
func (o *GetAuthMeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth me o k response has a 4xx status code
func (o *GetAuthMeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get auth me o k response has a 5xx status code
func (o *GetAuthMeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth me o k response a status code equal to that given
func (o *GetAuthMeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get auth me o k response
func (o *GetAuthMeOK) Code() int {
	return 200
}

func (o *GetAuthMeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/me][%d] getAuthMeOK %s", 200, payload)
}

func (o *GetAuthMeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/me][%d] getAuthMeOK %s", 200, payload)
}

func (o *GetAuthMeOK) GetPayload() any {
	return o.Payload
}

func (o *GetAuthMeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAuthMeUnauthorized creates a GetAuthMeUnauthorized with default headers values
func NewGetAuthMeUnauthorized() *GetAuthMeUnauthorized {
	return &GetAuthMeUnauthorized{}
}

/*
GetAuthMeUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAuthMeUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this get auth me unauthorized response has a 2xx status code
func (o *GetAuthMeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get auth me unauthorized response has a 3xx status code
func (o *GetAuthMeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth me unauthorized response has a 4xx status code
func (o *GetAuthMeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get auth me unauthorized response has a 5xx status code
func (o *GetAuthMeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth me unauthorized response a status code equal to that given
func (o *GetAuthMeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get auth me unauthorized response
func (o *GetAuthMeUnauthorized) Code() int {
	return 401
}

func (o *GetAuthMeUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/me][%d] getAuthMeUnauthorized %s", 401, payload)
}

func (o *GetAuthMeUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/me][%d] getAuthMeUnauthorized %s", 401, payload)
}

func (o *GetAuthMeUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetAuthMeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAuthMeNotFound creates a GetAuthMeNotFound with default headers values
func NewGetAuthMeNotFound() *GetAuthMeNotFound {
	return &GetAuthMeNotFound{}
}

/*
GetAuthMeNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAuthMeNotFound struct {
	Payload map[string]string
}

// IsSuccess returns true when this get auth me not found response has a 2xx status code
func (o *GetAuthMeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get auth me not found response has a 3xx status code
func (o *GetAuthMeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth me not found response has a 4xx status code
func (o *GetAuthMeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get auth me not found response has a 5xx status code
func (o *GetAuthMeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth me not found response a status code equal to that given
func (o *GetAuthMeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get auth me not found response
func (o *GetAuthMeNotFound) Code() int {
	return 404
}

func (o *GetAuthMeNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/me][%d] getAuthMeNotFound %s", 404, payload)
}

func (o *GetAuthMeNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/me][%d] getAuthMeNotFound %s", 404, payload)
}

func (o *GetAuthMeNotFound) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetAuthMeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
