// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAuthRefreshReader is a Reader for the PostAuthRefresh structure.
type PostAuthRefreshReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthRefreshReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthRefreshOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostAuthRefreshUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth/refresh] PostAuthRefresh", response, response.Code())
	}
}

// NewPostAuthRefreshOK creates a PostAuthRefreshOK with default headers values
func NewPostAuthRefreshOK() *PostAuthRefreshOK {
	return &PostAuthRefreshOK{}
}

/*
PostAuthRefreshOK describes a response with status code 200, with default header values.

OK
*/
type PostAuthRefreshOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse
}

// IsSuccess returns true when this post auth refresh o k response has a 2xx status code
func (o *PostAuthRefreshOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth refresh o k response has a 3xx status code
func (o *PostAuthRefreshOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth refresh o k response has a 4xx status code
func (o *PostAuthRefreshOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth refresh o k response has a 5xx status code
func (o *PostAuthRefreshOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth refresh o k response a status code equal to that given
func (o *PostAuthRefreshOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post auth refresh o k response
func (o *PostAuthRefreshOK) Code() int {
	return 200
}

func (o *PostAuthRefreshOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshOK %s", 200, payload)
}

func (o *PostAuthRefreshOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshOK %s", 200, payload)
}

func (o *PostAuthRefreshOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse {
	return o.Payload
}

func (o *PostAuthRefreshOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthRefreshUnauthorized creates a PostAuthRefreshUnauthorized with default headers values
func NewPostAuthRefreshUnauthorized() *PostAuthRefreshUnauthorized {
	return &PostAuthRefreshUnauthorized{}
}

/*
PostAuthRefreshUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAuthRefreshUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this post auth refresh unauthorized response has a 2xx status code
func (o *PostAuthRefreshUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth refresh unauthorized response has a 3xx status code
func (o *PostAuthRefreshUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth refresh unauthorized response has a 4xx status code
func (o *PostAuthRefreshUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth refresh unauthorized response has a 5xx status code
func (o *PostAuthRefreshUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth refresh unauthorized response a status code equal to that given
func (o *PostAuthRefreshUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post auth refresh unauthorized response
func (o *PostAuthRefreshUnauthorized) Code() int {
	return 401
}

func (o *PostAuthRefreshUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshUnauthorized %s", 401, payload)
}

func (o *PostAuthRefreshUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/refresh][%d] postAuthRefreshUnauthorized %s", 401, payload)
}

func (o *PostAuthRefreshUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostAuthRefreshUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
