// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAuthRegisterReader is a Reader for the PostAuthRegister structure.
type PostAuthRegisterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthRegisterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthRegisterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAuthRegisterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAuthRegisterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth/register] PostAuthRegister", response, response.Code())
	}
}

// NewPostAuthRegisterOK creates a PostAuthRegisterOK with default headers values
func NewPostAuthRegisterOK() *PostAuthRegisterOK {
	return &PostAuthRegisterOK{}
}

/*
PostAuthRegisterOK describes a response with status code 200, with default header values.

OK
*/
type PostAuthRegisterOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse
}

// IsSuccess returns true when this post auth register o k response has a 2xx status code
func (o *PostAuthRegisterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth register o k response has a 3xx status code
func (o *PostAuthRegisterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth register o k response has a 4xx status code
func (o *PostAuthRegisterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth register o k response has a 5xx status code
func (o *PostAuthRegisterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth register o k response a status code equal to that given
func (o *PostAuthRegisterOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post auth register o k response
func (o *PostAuthRegisterOK) Code() int {
	return 200
}

func (o *PostAuthRegisterOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/register][%d] postAuthRegisterOK %s", 200, payload)
}

func (o *PostAuthRegisterOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/register][%d] postAuthRegisterOK %s", 200, payload)
}

func (o *PostAuthRegisterOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse {
	return o.Payload
}

func (o *PostAuthRegisterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthRegisterBadRequest creates a PostAuthRegisterBadRequest with default headers values
func NewPostAuthRegisterBadRequest() *PostAuthRegisterBadRequest {
	return &PostAuthRegisterBadRequest{}
}

/*
PostAuthRegisterBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAuthRegisterBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this post auth register bad request response has a 2xx status code
func (o *PostAuthRegisterBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth register bad request response has a 3xx status code
func (o *PostAuthRegisterBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth register bad request response has a 4xx status code
func (o *PostAuthRegisterBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth register bad request response has a 5xx status code
func (o *PostAuthRegisterBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth register bad request response a status code equal to that given
func (o *PostAuthRegisterBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post auth register bad request response
func (o *PostAuthRegisterBadRequest) Code() int {
	return 400
}

func (o *PostAuthRegisterBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/register][%d] postAuthRegisterBadRequest %s", 400, payload)
}

func (o *PostAuthRegisterBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/register][%d] postAuthRegisterBadRequest %s", 400, payload)
}

func (o *PostAuthRegisterBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostAuthRegisterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthRegisterInternalServerError creates a PostAuthRegisterInternalServerError with default headers values
func NewPostAuthRegisterInternalServerError() *PostAuthRegisterInternalServerError {
	return &PostAuthRegisterInternalServerError{}
}

/*
PostAuthRegisterInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAuthRegisterInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this post auth register internal server error response has a 2xx status code
func (o *PostAuthRegisterInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth register internal server error response has a 3xx status code
func (o *PostAuthRegisterInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth register internal server error response has a 4xx status code
func (o *PostAuthRegisterInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth register internal server error response has a 5xx status code
func (o *PostAuthRegisterInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post auth register internal server error response a status code equal to that given
func (o *PostAuthRegisterInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post auth register internal server error response
func (o *PostAuthRegisterInternalServerError) Code() int {
	return 500
}

func (o *PostAuthRegisterInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/register][%d] postAuthRegisterInternalServerError %s", 500, payload)
}

func (o *PostAuthRegisterInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/register][%d] postAuthRegisterInternalServerError %s", 500, payload)
}

func (o *PostAuthRegisterInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostAuthRegisterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
