// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAuthLoginReader is a Reader for the PostAuthLogin structure.
type PostAuthLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAuthLoginBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAuthLoginUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth/login] PostAuthLogin", response, response.Code())
	}
}

// NewPostAuthLoginOK creates a PostAuthLoginOK with default headers values
func NewPostAuthLoginOK() *PostAuthLoginOK {
	return &PostAuthLoginOK{}
}

/*
PostAuthLoginOK describes a response with status code 200, with default header values.

OK
*/
type PostAuthLoginOK struct {
	Payload *models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse
}

// IsSuccess returns true when this post auth login o k response has a 2xx status code
func (o *PostAuthLoginOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth login o k response has a 3xx status code
func (o *PostAuthLoginOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth login o k response has a 4xx status code
func (o *PostAuthLoginOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth login o k response has a 5xx status code
func (o *PostAuthLoginOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth login o k response a status code equal to that given
func (o *PostAuthLoginOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post auth login o k response
func (o *PostAuthLoginOK) Code() int {
	return 200
}

func (o *PostAuthLoginOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/login][%d] postAuthLoginOK %s", 200, payload)
}

func (o *PostAuthLoginOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/login][%d] postAuthLoginOK %s", 200, payload)
}

func (o *PostAuthLoginOK) GetPayload() *models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse {
	return o.Payload
}

func (o *PostAuthLoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComFlotioDevCoreAPIInternalModulesUserModelAuthResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthLoginBadRequest creates a PostAuthLoginBadRequest with default headers values
func NewPostAuthLoginBadRequest() *PostAuthLoginBadRequest {
	return &PostAuthLoginBadRequest{}
}

/*
PostAuthLoginBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAuthLoginBadRequest struct {
	Payload map[string]string
}

// IsSuccess returns true when this post auth login bad request response has a 2xx status code
func (o *PostAuthLoginBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth login bad request response has a 3xx status code
func (o *PostAuthLoginBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth login bad request response has a 4xx status code
func (o *PostAuthLoginBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth login bad request response has a 5xx status code
func (o *PostAuthLoginBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth login bad request response a status code equal to that given
func (o *PostAuthLoginBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post auth login bad request response
func (o *PostAuthLoginBadRequest) Code() int {
	return 400
}

func (o *PostAuthLoginBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/login][%d] postAuthLoginBadRequest %s", 400, payload)
}

func (o *PostAuthLoginBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/login][%d] postAuthLoginBadRequest %s", 400, payload)
}

func (o *PostAuthLoginBadRequest) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostAuthLoginBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthLoginUnauthorized creates a PostAuthLoginUnauthorized with default headers values
func NewPostAuthLoginUnauthorized() *PostAuthLoginUnauthorized {
	return &PostAuthLoginUnauthorized{}
}

/*
PostAuthLoginUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAuthLoginUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this post auth login unauthorized response has a 2xx status code
func (o *PostAuthLoginUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth login unauthorized response has a 3xx status code
func (o *PostAuthLoginUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth login unauthorized response has a 4xx status code
func (o *PostAuthLoginUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth login unauthorized response has a 5xx status code
func (o *PostAuthLoginUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth login unauthorized response a status code equal to that given
func (o *PostAuthLoginUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post auth login unauthorized response
func (o *PostAuthLoginUnauthorized) Code() int {
	return 401
}

func (o *PostAuthLoginUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/login][%d] postAuthLoginUnauthorized %s", 401, payload)
}

func (o *PostAuthLoginUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/login][%d] postAuthLoginUnauthorized %s", 401, payload)
}

func (o *PostAuthLoginUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *PostAuthLoginUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
