// Code generated by go-swagger; DO NOT EDIT.

package flutter

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/flotio-dev/cli/pkg/api/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetFlutterVersionsReader is a Reader for the GetFlutterVersions structure.
type GetFlutterVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFlutterVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetFlutterVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /flutter/versions] GetFlutterVersions", response, response.Code())
	}
}

// NewGetFlutterVersionsOK creates a GetFlutterVersionsOK with default headers values
func NewGetFlutterVersionsOK() *GetFlutterVersionsOK {
	return &GetFlutterVersionsOK{}
}

/*
GetFlutterVersionsOK describes a response with status code 200, with default header values.

OK
*/
type GetFlutterVersionsOK struct {
	Payload *models.InternalModulesProjectHandlerFlutterVersionsResponse
}

// IsSuccess returns true when this get flutter versions o k response has a 2xx status code
func (o *GetFlutterVersionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get flutter versions o k response has a 3xx status code
func (o *GetFlutterVersionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get flutter versions o k response has a 4xx status code
func (o *GetFlutterVersionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get flutter versions o k response has a 5xx status code
func (o *GetFlutterVersionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get flutter versions o k response a status code equal to that given
func (o *GetFlutterVersionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get flutter versions o k response
func (o *GetFlutterVersionsOK) Code() int {
	return 200
}

func (o *GetFlutterVersionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /flutter/versions][%d] getFlutterVersionsOK %s", 200, payload)
}

func (o *GetFlutterVersionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /flutter/versions][%d] getFlutterVersionsOK %s", 200, payload)
}

func (o *GetFlutterVersionsOK) GetPayload() *models.InternalModulesProjectHandlerFlutterVersionsResponse {
	return o.Payload
}

func (o *GetFlutterVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalModulesProjectHandlerFlutterVersionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
